import { api } from './api.js';
import { state } from './state.js';
import { beginAvatarAnalyzing,endAvatarAnalyzing } from './avatar.js';

const $=s=>document.querySelector(s);
const DEFAULT_PRIVACY={eventTitles:true,eventNotes:false,taskTitles:true,taskNotes:false,financeTotals:true,portfolioPositions:false,financeJournal:false,fitnessMetrics:true};
let notify=()=>{},currentReport=null,historyPage=0;const HISTORY_SIZE=8;

function reports(){return state.ai?.reports||[];}
function fmtDate(v){if(!v)return'—';try{return new Date(v).toLocaleString('en-SG',{timeZone:'Asia/Singapore',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});}catch{return String(v);}}
function scoreClass(n){n=Number(n)||0;return n>=80?'good':n>=60?'watch':'bad';}
function setText(id,v){const e=$(id);if(e)e.textContent=v??'—';}
function latest(){return [...reports()].sort((a,b)=>String(b.generatedAt).localeCompare(String(a.generatedAt)))[0]||null;}
function sourceLabel(r){return r?.payload?.meta?.source==='local-fallback'?'LOCAL FALLBACK':String(r?.payload?.meta?.model||'GEMINI').toUpperCase();}
function renderBrief(){const r=latest();currentReport=r;if(!r){setText('#aiSeverity','STANDBY');setText('#aiHeadline','No intelligence report yet.');setText('#aiSummary','Generate a DAILY or WEEKLY brief from your current Neon Ops data.');setText('#aiGenerated','NOT YET');setText('#aiBriefModel','GEMINI 3.8 FLASH');return;}setText('#aiSeverity',r.severity||'STABLE');$('#aiSeverity').dataset.severity=String(r.severity||'STABLE').toLowerCase();setText('#aiHeadline',r.headline);setText('#aiSummary',r.summary);setText('#aiGenerated',fmtDate(r.generatedAt));setText('#aiBriefModel',sourceLabel(r));}
function fillList(id,items,empty){const root=$(id);if(!root)return;root.replaceChildren();const rows=Array.isArray(items)?items:[];if(!rows.length){const d=document.createElement('div');d.className='ai-empty';d.textContent=empty;root.append(d);return;}for(const text of rows){const d=document.createElement('div');d.className='ai-list-item';d.textContent=text;root.append(d);}}
function renderScores(scores={}){for(const [key,id] of [['operations','#aiScoreOps'],['workload','#aiScoreWorkload'],['discipline','#aiScoreDiscipline'],['finance','#aiScoreFinance'],['fitness','#aiScoreFitness']]){const el=$(id),v=Math.round(Number(scores?.[key])||0);if(el){el.textContent=String(v);el.dataset.band=scoreClass(v);}}}
function renderReport(r){if(!r)return;currentReport=r;setText('#aiReportScope',r.scope);setText('#aiReportSeverity',r.severity);$('#aiReportSeverity').dataset.severity=String(r.severity||'STABLE').toLowerCase();setText('#aiReportTime',fmtDate(r.generatedAt));setText('#aiReportModel',sourceLabel(r));setText('#aiReportHeadline',r.headline);setText('#aiReportSummary',r.summary);const p=r.payload||{};renderScores(p.scores||{});fillList('#aiInsights',p.insights,'NO INSIGHTS');fillList('#aiActions',p.actions,'NO ACTIONS');fillList('#aiStrengths',p.strengths,'NO STRENGTHS FLAGGED');fillList('#aiWeaknesses',p.weaknesses,'NO WEAKNESSES FLAGGED');}
async function loadSettings(){try{const d=await api('/api/v8/ai/settings');state.ai.settings={privacy:{...DEFAULT_PRIVACY,...(d.privacy||{})},thinkingLevel:d.thinkingLevel||'medium',model:d.model||'gemini-3.8-flash',configured:!!d.configured};renderSettings();}catch(e){notify(e.message,true);}}
function renderSettings(){const s=state.ai.settings||{},p={...DEFAULT_PRIVACY,...(s.privacy||{})};const map={aiPrivacyEventTitles:'eventTitles',aiPrivacyEventNotes:'eventNotes',aiPrivacyTaskTitles:'taskTitles',aiPrivacyTaskNotes:'taskNotes',aiPrivacyFinanceTotals:'financeTotals',aiPrivacyPositions:'portfolioPositions',aiPrivacyJournal:'financeJournal',aiPrivacyFitness:'fitnessMetrics'};for(const [id,k] of Object.entries(map)){const el=$('#'+id);if(el)el.checked=!!p[k];}if($('#aiThinkingLevel'))$('#aiThinkingLevel').value=s.thinkingLevel||'medium';setText('#aiModelLabel',String(s.model||'gemini-3.8-flash').toUpperCase());setText('#aiApiState',s.configured?'READY':'NOT CONFIGURED');}
async function saveSettings(){const p={eventTitles:$('#aiPrivacyEventTitles').checked,eventNotes:$('#aiPrivacyEventNotes').checked,taskTitles:$('#aiPrivacyTaskTitles').checked,taskNotes:$('#aiPrivacyTaskNotes').checked,financeTotals:$('#aiPrivacyFinanceTotals').checked,portfolioPositions:$('#aiPrivacyPositions').checked,financeJournal:$('#aiPrivacyJournal').checked,fitnessMetrics:$('#aiPrivacyFitness').checked};try{const d=await api('/api/v8/ai/settings',{method:'PATCH',body:{privacy:p,thinkingLevel:$('#aiThinkingLevel').value}});state.ai.settings={...(state.ai.settings||{}),privacy:d.privacy,thinkingLevel:d.thinkingLevel};notify('AI PRIVACY SETTINGS SAVED');renderSettings();}catch(e){notify(e.message,true);}}
async function generate(scope,thinkingLevel=null){scope=String(scope||'DAILY').toUpperCase();const buttons=[...document.querySelectorAll('[data-ai-generate]')];buttons.forEach(b=>{b.disabled=true;b.dataset.old=b.textContent;b.textContent='ANALYZING…';});beginAvatarAnalyzing(`GEMINI ${scope}`);try{const d=await api('/api/v8/ai/generate',{method:'POST',body:{scope,...(thinkingLevel?{thinkingLevel}:{})}});state.ai.reports=state.ai.reports||[];state.ai.reports.unshift(d.report);renderBrief();renderReport(d.report);if($('#aiDialog')&&!$('#aiDialog').open)$('#aiDialog').showModal();notify(d.report?.payload?.meta?.source==='local-fallback'?'LOCAL FALLBACK REPORT GENERATED':'GEMINI INTELLIGENCE COMPLETE',d.report?.payload?.meta?.source==='local-fallback');}catch(e){notify(e.message,true);}finally{endAvatarAnalyzing();buttons.forEach(b=>{b.disabled=false;b.textContent=b.dataset.old||'GENERATE';});}}
function openLatest(){const r=latest();if(!r){$('#aiDialog').showModal();return;}renderReport(r);$('#aiDialog').showModal();}
function renderHistory(){const all=[...reports()].sort((a,b)=>String(b.generatedAt).localeCompare(String(a.generatedAt))),pages=Math.max(1,Math.ceil(all.length/HISTORY_SIZE));historyPage=Math.min(historyPage,pages-1);const slice=all.slice(historyPage*HISTORY_SIZE,(historyPage+1)*HISTORY_SIZE),root=$('#aiHistoryList');root.replaceChildren();if(!slice.length){const d=document.createElement('div');d.className='ai-empty';d.textContent='NO REPORT HISTORY';root.append(d);}for(const r of slice){const row=document.createElement('div');row.className='ai-history-row';const open=document.createElement('button');open.type='button';open.className='ai-history-open';open.innerHTML=`<span>${r.scope} // ${r.severity}</span><b></b><small>${fmtDate(r.generatedAt)}</small>`;open.querySelector('b').textContent=r.headline;open.onclick=()=>{$('#aiHistoryDialog').close();renderReport(r);$('#aiDialog').showModal();};const del=document.createElement('button');del.type='button';del.className='danger small';del.textContent='DELETE';del.onclick=async()=>{if(!confirm('Delete this intelligence report?'))return;try{await api(`/api/v8/ai/reports/${encodeURIComponent(r.id)}`,{method:'DELETE'});state.ai.reports=state.ai.reports.filter(x=>x.id!==r.id);renderHistory();renderBrief();notify('AI REPORT DELETED');}catch(e){notify(e.message,true);}};row.append(open,del);root.append(row);}setText('#aiHistoryPager',`${all.length?historyPage+1:0} / ${all.length?pages:0}`);$('#aiHistoryPrev').disabled=historyPage<=0;$('#aiHistoryNext').disabled=historyPage>=pages-1;}
function openHistory(){historyPage=0;renderHistory();$('#aiHistoryDialog').showModal();}
function bind(){
  $('#aiQuickGenerate').onclick=()=>generate($('#aiScopeQuick').value);$('#aiOpenBtn').onclick=openLatest;$('#aiHistoryBtn').onclick=openHistory;
  $('#aiGenerateFull').onclick=()=>generate($('#aiScopeFull').value,$('#aiThinkingLevel').value);$('#aiSavePrivacy').onclick=saveSettings;$('#aiOpenHistoryFromReport').onclick=()=>{$('#aiDialog').close();openHistory();};
  $('#aiHistoryPrev').onclick=()=>{historyPage=Math.max(0,historyPage-1);renderHistory();};$('#aiHistoryNext').onclick=()=>{historyPage++;renderHistory();};
}
export async function initAI(toast){notify=toast;state.ai=state.ai||{reports:[],settings:{}};await loadSettings();bind();renderBrief();}
export function refreshAI(){renderBrief();}
