import { api,connectGoogle } from './api.js';
import { state } from './state.js';
import { initCalendar,refreshCalendar } from './calendar.js';
import { initTasks,renderTasks } from './tasks.js';
import { initFitness,refreshFitness } from './fitness.js';
import { initFinance,refreshFinance } from './finance.js';
const $=s=>document.querySelector(s);let toastTimer;
function toast(msg,error=false){const el=$('#toast');el.textContent=(error?'ERROR // ':'')+msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3200);updateHud();}
function googleMeta(){return state.integrations?.google||null;}
function updateHud(){const active=state.tasks.filter(t=>t.status==='active'),now=Date.now(),overdue=active.filter(t=>t.dueAt&&new Date(t.dueAt).getTime()<now),urgent=active.filter(t=>t.dueAt&&new Date(t.dueAt).getTime()>=now&&new Date(t.dueAt).getTime()<now+86400000);let mood='RELAXED',text='No urgent objectives detected.';if(overdue.filter(t=>['high','critical'].includes(t.priority)).length>=2||overdue.length>=4){mood='PANIC';text='Multiple overdue objectives require action.';}else if(urgent.length>=2||active.length>=6){mood='ANXIOUS';text='Deadline pressure is rising.';}else if(active.length){mood='FOCUSED';text='Operational workload within normal range.';}$('#nexusMood').textContent=mood;$('#taskPressure').textContent=`${active.length} ACTIVE`;$('#pressureText').textContent=text;$('#statusEvents').textContent=state.events.length;$('#statusTasks').textContent=state.tasks.length;const g=googleMeta();$('#statusGoogle').textContent=g?'CONNECTED':'DISCONNECTED';$('#statusGoogle').style.color=g?'var(--green)':'var(--amber)';const last=g?.metadata?.lastSyncAt;$('#statusSync').textContent=last?new Date(last).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'NOT YET';}
function clock(){const parts=new Intl.DateTimeFormat('en-SG',{timeZone:'Asia/Singapore',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(new Date());$('#clock').textContent=`${parts.filter(x=>['hour','minute','second'].includes(x.type)).map(x=>x.value).join(':')} SGT`;}
async function loadBootstrap(){const data=await api('/api/v8/bootstrap');state.user=data.user;state.events=data.events||[];state.tasks=data.tasks||[];state.fitness=data.fitness||{movements:[],sessions:[]};state.finance=data.finance||{settings:{currency:'SGD',startingBalance:0,portfolioCash:0,cashUpColor:'#2fd69a',cashDownColor:'#ff405c'},transactions:[],positions:[],journal:[]};state.integrations=data.integrations||{};return data;}
async function syncNow(){const btn=$('#syncGoogleBtn');btn.disabled=true;const old=btn.textContent;btn.textContent='SYNCING…';try{const result=await api('/api/v8/sync/google',{method:'POST'});await loadBootstrap();refreshCalendar();renderTasks(toast);refreshFinance();updateHud();const pulled=(result.pull?.calendar?.inserted||0)+(result.pull?.calendar?.updated||0)+(result.pull?.tasks?.inserted||0)+(result.pull?.tasks?.updated||0);toast(`GOOGLE SYNC COMPLETE // ${pulled} REMOTE RECORDS`);}catch(e){toast(e.message,true);}finally{btn.disabled=false;btn.textContent=old;}}
async function boot(){clock();setInterval(clock,1000);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());try{const health=await api('/health');$('#apiStatus').textContent=`API // ${health.version}`;$('#apiStatus').style.color='var(--green)';}catch{$('#apiStatus').textContent='API // OFFLINE';}
try{await loadBootstrap();$('#authStatus').textContent='AUTH // SECURE';$('#authStatus').style.color='var(--green)';$('#statusAuth').textContent='SECURE';initCalendar(toast);initTasks(toast);initFitness(toast);initFinance(toast);initTabs();$('#syncGoogleBtn').onclick=syncNow;updateHud();}catch(e){if(e.status===401){$('#authStatus').textContent='AUTH // REQUIRED';$('#statusAuth').textContent='REQUIRED';const btn=document.createElement('button');btn.className='primary';btn.textContent='CONNECT GOOGLE';btn.onclick=connectGoogle;document.querySelector('.ops-grid').prepend(btn);}else toast(e.message,true);}$('#bootCover').classList.add('off');setTimeout(()=>$('#bootCover').remove(),300);}
function initTabs(){document.querySelectorAll('.tab[data-page]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab[data-page]').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===btn.dataset.page));if(btn.dataset.page==='pageFitness')setTimeout(()=>refreshFitness(),0);if(btn.dataset.page==='pageFinance')setTimeout(()=>refreshFinance(),0);});}
window.addEventListener('resize',()=>{if(state.user){refreshCalendar();renderTasks(toast);refreshFitness();refreshFinance();}});boot();
