import { api,apiBlob,apiForm } from './api.js';
import { state } from './state.js';

const $=s=>document.querySelector(s);
const DEFAULT_APPEARANCE={preset:'TACTICAL',hudMaxWidth:1900,panelGap:14,panelPadding:16,radius:15,borderOpacity:.62,shadowIntensity:.30,interfaceScale:1,headingScale:1,telemetryScale:1,density:'COMFORTABLE',mobileDensity:'COMPACT',palette:{cyan:'#00d9ff',mag:'#ff3ea5',red:'#ff405c',amber:'#ffba4a',green:'#6ee7a7',violet:'#8b6cff'}};
const PRESETS={
  TACTICAL:{...DEFAULT_APPEARANCE},
  EDITORIAL:{...DEFAULT_APPEARANCE,preset:'EDITORIAL',hudMaxWidth:1780,panelGap:18,panelPadding:19,radius:12,borderOpacity:.48,shadowIntensity:.20,interfaceScale:1.02,headingScale:1.16,telemetryScale:.94,density:'COMFORTABLE',mobileDensity:'COMFORTABLE',palette:{cyan:'#79d9e8',mag:'#d96ea8',red:'#e26b79',amber:'#d7ae69',green:'#80c8a2',violet:'#9482c8'}},
  DENSE:{...DEFAULT_APPEARANCE,preset:'DENSE',hudMaxWidth:2200,panelGap:8,panelPadding:11,radius:7,borderOpacity:.72,shadowIntensity:.16,interfaceScale:.90,headingScale:.92,telemetryScale:.88,density:'DENSE',mobileDensity:'DENSE'},
  MINIMAL:{...DEFAULT_APPEARANCE,preset:'MINIMAL',hudMaxWidth:1840,panelGap:16,panelPadding:17,radius:9,borderOpacity:.30,shadowIntensity:.08,interfaceScale:.96,headingScale:1.02,telemetryScale:.88,density:'COMFORTABLE',mobileDensity:'COMPACT',palette:{cyan:'#71cbd6',mag:'#ba7398',red:'#d87882',amber:'#c7a66f',green:'#83bba0',violet:'#9186b4'}}
};
const SECTIONS=[
  ['GLOBAL_UI','Global / UI'],['BRAND_TITLE','Brand / Title'],['PANEL_HEADINGS','Panel Headings'],['TELEMETRY','Telemetry / Numbers'],['CALENDAR','Calendar'],['FITNESS','Fitness'],['FINANCE','Finance'],['CUSTOMIZE','Customize'],['MEDIA','Media']
];
const CSS_VARS={GLOBAL_UI:'--body-font',BRAND_TITLE:'--font-brand',PANEL_HEADINGS:'--editorial',TELEMETRY:'--telemetry',CALENDAR:'--font-calendar',FITNESS:'--font-fitness',FINANCE:'--font-finance',CUSTOMIZE:'--font-customize',MEDIA:'--font-media'};
const DEFAULT_FONT_VARS={
  GLOBAL_UI:'Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif',
  BRAND_TITLE:'"Times New Roman",Times,serif',PANEL_HEADINGS:'"Times New Roman",Times,serif',
  TELEMETRY:'ui-monospace,SFMono-Regular,Menlo,Consolas,monospace',CALENDAR:'Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif',
  FITNESS:'Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif',FINANCE:'Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif',
  CUSTOMIZE:'Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif',MEDIA:'Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif'
};
let notify=()=>{},bound=false,draft=null,previewAssetId=null;
const loadedFonts=new Map();
function clone(v){return JSON.parse(JSON.stringify(v));}
function appearance(){return state.appearance?.settings||DEFAULT_APPEARANCE;}
function densityMult(v){return v==='DENSE'?.68:v==='COMPACT'?.82:1;}
function alphaHex(hex,alpha){const h=hex.replace('#','');const n=parseInt(h,16);return `rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${alpha})`;}
function setVar(k,v){document.documentElement.style.setProperty(k,v);}
function applyAppearance(a){
  const d=densityMult(a.density),m=densityMult(a.mobileDensity),p=a.palette||DEFAULT_APPEARANCE.palette;
  setVar('--hud-max-width',`${a.hudMaxWidth}px`);setVar('--panel-gap-effective',`${Math.max(5,a.panelGap*d).toFixed(1)}px`);setVar('--panel-padding-effective',`${Math.max(8,a.panelPadding*d).toFixed(1)}px`);setVar('--panel-gap-mobile',`${Math.max(5,a.panelGap*m).toFixed(1)}px`);setVar('--panel-padding-mobile',`${Math.max(8,a.panelPadding*m).toFixed(1)}px`);setVar('--radius',`${a.radius}px`);
  setVar('--interface-scale',a.interfaceScale);setVar('--heading-scale',a.headingScale);setVar('--telemetry-scale',a.telemetryScale);setVar('--line',alphaHex('#555865',a.borderOpacity));setVar('--line-soft',alphaHex('#555865',Math.max(.10,a.borderOpacity*.52)));setVar('--shadow',`0 18px 70px rgba(0,0,0,${a.shadowIntensity})`);
  for(const k of ['cyan','mag','red','amber','green','violet'])setVar(`--${k}`,p[k]);
  setVar('--accent-primary',p.cyan);setVar('--accent-selected',p.mag);setVar('--accent-danger',p.red);setVar('--accent-warning',p.amber);setVar('--accent-success',p.green);setVar('--accent-secondary',p.violet);
  document.documentElement.dataset.density=a.density;document.documentElement.dataset.mobileDensity=a.mobileDensity;
  window.dispatchEvent(new CustomEvent('neon:themechange',{detail:{palette:p}}));
}
function applyDefaultFonts(){for(const [section,varName] of Object.entries(CSS_VARS))setVar(varName,DEFAULT_FONT_VARS[section]);setVar('--calendar-time-font','var(--font-calendar)');setVar('--font-panel','var(--editorial)');}
async function loadFontAsset(asset){if(!asset)return null;if(loadedFonts.has(asset.id))return loadedFonts.get(asset.id);const family=asset.metadata?.fontFamily||`NeonFont_${asset.id.replace(/[^a-zA-Z0-9]/g,'').slice(0,18)}`;const blob=await apiBlob(`/api/v8/assets/${encodeURIComponent(asset.id)}`);const url=URL.createObjectURL(blob);const face=new FontFace(family,`url(${JSON.stringify(url)})`);await face.load();document.fonts.add(face);const record={family,face,url};loadedFonts.set(asset.id,record);return record;}
async function applyAssignments(){applyDefaultFonts();const assets=state.appearance?.assets||[];for(const a of state.appearance?.assignments||[]){const asset=assets.find(x=>x.id===a.assetId);if(!asset)continue;try{const loaded=await loadFontAsset(asset);const v=`"${loaded.family}", ${DEFAULT_FONT_VARS[a.sectionKey]||'sans-serif'}`;setVar(CSS_VARS[a.sectionKey],v);if(a.sectionKey==='CALENDAR')setVar('--calendar-time-font',v);if(a.sectionKey==='PANEL_HEADINGS')setVar('--font-panel',v);}catch(e){console.warn('Font load failed',asset.originalName,e);}}
}
async function refreshData(){const data=await api('/api/v8/appearance');state.appearance={settings:data.appearance||clone(DEFAULT_APPEARANCE),assets:data.assets||[],assignments:data.assignments||[]};draft=clone(state.appearance.settings);applyAppearance(draft);await applyAssignments();}
function v(id,val){const el=$(id);if(el)el.value=val;}
function text(id,val){const el=$(id);if(el)el.textContent=val;}
function syncForm(){const a=draft||clone(DEFAULT_APPEARANCE);v('#appearanceHudWidth',a.hudMaxWidth);v('#appearancePanelGap',a.panelGap);v('#appearancePanelPadding',a.panelPadding);v('#appearanceRadius',a.radius);v('#appearanceBorder',Math.round(a.borderOpacity*100));v('#appearanceShadow',Math.round(a.shadowIntensity*100));v('#appearanceScale',Math.round(a.interfaceScale*100));v('#appearanceHeadingScale',Math.round(a.headingScale*100));v('#appearanceTelemetryScale',Math.round(a.telemetryScale*100));v('#appearanceDensity',a.density);v('#appearanceMobileDensity',a.mobileDensity);for(const k of ['cyan','mag','red','amber','green','violet'])v(`#appearanceColor${k[0].toUpperCase()+k.slice(1)}`,a.palette[k]);updateLabels();}
function readForm(){return{...draft,hudMaxWidth:Number($('#appearanceHudWidth').value),panelGap:Number($('#appearancePanelGap').value),panelPadding:Number($('#appearancePanelPadding').value),radius:Number($('#appearanceRadius').value),borderOpacity:Number($('#appearanceBorder').value)/100,shadowIntensity:Number($('#appearanceShadow').value)/100,interfaceScale:Number($('#appearanceScale').value)/100,headingScale:Number($('#appearanceHeadingScale').value)/100,telemetryScale:Number($('#appearanceTelemetryScale').value)/100,density:$('#appearanceDensity').value,mobileDensity:$('#appearanceMobileDensity').value,palette:{cyan:$('#appearanceColorCyan').value,mag:$('#appearanceColorMag').value,red:$('#appearanceColorRed').value,amber:$('#appearanceColorAmber').value,green:$('#appearanceColorGreen').value,violet:$('#appearanceColorViolet').value}};}
function updateLabels(){text('#appearanceHudWidthValue',`${$('#appearanceHudWidth').value}px`);text('#appearancePanelGapValue',`${$('#appearancePanelGap').value}px`);text('#appearancePanelPaddingValue',`${$('#appearancePanelPadding').value}px`);text('#appearanceRadiusValue',`${$('#appearanceRadius').value}px`);text('#appearanceBorderValue',`${$('#appearanceBorder').value}%`);text('#appearanceShadowValue',`${$('#appearanceShadow').value}%`);text('#appearanceScaleValue',`${$('#appearanceScale').value}%`);text('#appearanceHeadingScaleValue',`${$('#appearanceHeadingScale').value}%`);text('#appearanceTelemetryScaleValue',`${$('#appearanceTelemetryScale').value}%`);}
function liveFromForm(){draft=readForm();draft.preset='CUSTOM';applyAppearance(draft);updateLabels();renderPreview();}
function renderPreview(){const root=$('#appearancePreview');if(!root)return;root.style.setProperty('--preview-cyan',draft.palette.cyan);root.querySelector('.appearance-preview-title').textContent='NEON OPERATIONS CENTER';root.querySelector('.appearance-preview-meta').textContent=`OPS // 01   SGT 16:42   SYNC // ONLINE`;root.querySelector('.appearance-preview-value').textContent='S$ 12,840.42';}
function renderFontLibrary(){const root=$('#fontLibrary');if(!root)return;root.innerHTML='';const assets=state.appearance?.assets||[];if(!assets.length){root.innerHTML='<div class="appearance-empty">NO CUSTOM FONTS UPLOADED</div>';return;}for(const asset of assets){const row=document.createElement('div');row.className='font-library-row';const info=document.createElement('div');info.innerHTML=`<b>${escapeHtml(asset.originalName)}</b><span>${escapeHtml((asset.metadata?.extension||'font').toUpperCase())} // ${formatBytes(asset.sizeBytes)}</span>`;const preview=document.createElement('button');preview.type='button';preview.className='ghost small';preview.textContent='PREVIEW';preview.onclick=async()=>{try{const f=await loadFontAsset(asset);previewAssetId=asset.id;const p=$('#fontPreviewSample');p.style.fontFamily=`"${f.family}", sans-serif`;$('#fontPreviewName').textContent=asset.originalName;}catch(e){notify(e.message,true);}};const del=document.createElement('button');del.type='button';del.className='danger small';del.textContent='DELETE';del.onclick=()=>deleteFont(asset);row.append(info,preview,del);root.append(row);}}
function renderAssignments(){const root=$('#fontAssignments');if(!root)return;root.innerHTML='';const assets=state.appearance?.assets||[],assigned=state.appearance?.assignments||[];for(const [key,label] of SECTIONS){const row=document.createElement('div');row.className='font-assignment-row';const lab=document.createElement('div');lab.innerHTML=`<b>${label}</b><span>${scopeDescription(key)}</span>`;const select=document.createElement('select');select.innerHTML='<option value="">SYSTEM DEFAULT</option>'+assets.map(a=>`<option value="${a.id}">${escapeHtml(a.originalName)}</option>`).join('');select.value=assigned.find(x=>x.sectionKey===key)?.assetId||'';const apply=document.createElement('button');apply.type='button';apply.className='ghost small';apply.textContent='APPLY';apply.onclick=()=>saveAssignment(key,select.value);row.append(lab,select,apply);root.append(row);}}
function scopeDescription(k){return({GLOBAL_UI:'General controls and body copy',BRAND_TITLE:'Main NEON OPS brand',PANEL_HEADINGS:'Panel and module headings',TELEMETRY:'Status labels and numeric telemetry',CALENDAR:'Calendar event/time typography',FITNESS:'Fitness workspace',FINANCE:'Finance workspace',CUSTOMIZE:'Customize workspace',MEDIA:'Spotify and media workspace'})[k]||'';}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function formatBytes(n){n=Number(n)||0;return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;}
async function saveAssignment(section,assetId){try{if(assetId){await api(`/api/v8/fonts/assignments/${encodeURIComponent(section)}`,{method:'PUT',body:{assetId}});}else await api(`/api/v8/fonts/assignments/${encodeURIComponent(section)}`,{method:'DELETE'});await refreshData();renderAll();notify(`${section.replaceAll('_',' ')} FONT UPDATED`);}catch(e){notify(e.message,true);}}
async function deleteFont(asset){if(!confirm(`Delete ${asset.originalName}? Any sections using it will return to their default font.`))return;try{await api(`/api/v8/fonts/assets/${encodeURIComponent(asset.id)}`,{method:'DELETE'});const loaded=loadedFonts.get(asset.id);if(loaded){document.fonts.delete(loaded.face);URL.revokeObjectURL(loaded.url);loadedFonts.delete(asset.id);}if(previewAssetId===asset.id){previewAssetId=null;$('#fontPreviewSample').style.fontFamily='var(--body-font)';$('#fontPreviewName').textContent='SYSTEM DEFAULT';}await refreshData();renderAll();notify('FONT ASSET DELETED');}catch(e){notify(e.message,true);}}
function renderAll(){syncForm();renderPreview();renderFontLibrary();renderAssignments();}
function bindAppearanceForm(){const ids=['#appearanceHudWidth','#appearancePanelGap','#appearancePanelPadding','#appearanceRadius','#appearanceBorder','#appearanceShadow','#appearanceScale','#appearanceHeadingScale','#appearanceTelemetryScale','#appearanceDensity','#appearanceMobileDensity','#appearanceColorCyan','#appearanceColorMag','#appearanceColorRed','#appearanceColorAmber','#appearanceColorGreen','#appearanceColorViolet'];for(const id of ids){const el=$(id);if(el)el.addEventListener(el.tagName==='SELECT'||el.type==='color'?'change':'input',liveFromForm);}document.querySelectorAll('[data-appearance-preset]').forEach(btn=>btn.onclick=()=>{draft=clone(PRESETS[btn.dataset.appearancePreset]||DEFAULT_APPEARANCE);syncForm();applyAppearance(draft);renderPreview();notify(`${btn.dataset.appearancePreset} PRESET PREVIEW // SAVE TO KEEP`);});
  $('#appearanceForm').onsubmit=async e=>{e.preventDefault();try{draft=readForm();const out=await api('/api/v8/appearance',{method:'PATCH',body:draft});state.appearance.settings=out.appearance;draft=clone(out.appearance);applyAppearance(draft);syncForm();notify('HUD APPEARANCE SAVED');}catch(err){notify(err.message,true);}};
  $('#resetAppearanceBtn').onclick=async()=>{if(!confirm('Reset HUD appearance to the V8 tactical defaults? Fonts are not deleted.'))return;try{const out=await api('/api/v8/appearance',{method:'DELETE'});state.appearance.settings=out.appearance;draft=clone(out.appearance);applyAppearance(draft);syncForm();notify('HUD APPEARANCE RESET');}catch(e){notify(e.message,true);}};
}
function bindFontUi(){$('#uploadFontBtn').onclick=()=>$('#fontInput').click();$('#fontInput').onchange=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;const btn=$('#uploadFontBtn'),old=btn.textContent;btn.disabled=true;btn.textContent='UPLOADING…';try{const fd=new FormData();fd.append('file',file);const out=await apiForm('/api/v8/fonts/assets',fd);state.appearance.assets.unshift(out.asset);renderFontLibrary();renderAssignments();notify('FONT UPLOADED // ASSIGN IT TO A SECTION');}catch(err){notify(err.message,true);}finally{btn.disabled=false;btn.textContent=old;}};}
function bindUi(){if(bound)return;bound=true;bindAppearanceForm();bindFontUi();}
export async function initAppearance(onNotify){notify=onNotify||notify;bindUi();try{await refreshData();renderAll();}catch(e){notify(e.message,true);}}
export async function refreshAppearance(){try{await refreshData();renderAll();}catch(e){notify(e.message,true);}}
