import { api } from './api.js';
import { state,upsert,remove } from './state.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let toast=()=>{},cashChart=null,cashSeries=null,cashResize=null,cashTimeMeta=new Map(),txPage=0,journalPage=0;
const replay={mode:false,playing:false,speed:'1',monthKey:null,months:[],data:[],cumulative:[],position:0,rendered:0,startBalance:0,lastTs:0,carry:0,raf:0};
const TX_PAGE_SIZE=8,JOURNAL_PAGE_SIZE=5;

function money(v){const currency=state.finance?.settings?.currency||'SGD';try{return new Intl.NumberFormat('en-SG',{style:'currency',currency,maximumFractionDigits:2}).format(Number(v)||0)}catch{return `${currency} ${(Number(v)||0).toFixed(2)}`}}
function pct(v){const n=Number(v)||0;return `${n>=0?'+':''}${n.toFixed(2)}%`}
function localInput(iso){if(!iso)return'';const d=new Date(iso),pad=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function finance(){state.finance??={settings:{currency:'SGD',startingBalance:0,portfolioCash:0,cashUpColor:'#2fd69a',cashDownColor:'#ff405c'},transactions:[],positions:[],journal:[]};state.finance.settings??={currency:'SGD',startingBalance:0,portfolioCash:0,cashUpColor:'#2fd69a',cashDownColor:'#ff405c'};state.finance.transactions??=[];state.finance.positions??=[];state.finance.journal??=[];return state.finance;}
function sortedTransactions(){return [...finance().transactions].sort((a,b)=>new Date(a.occurredAt)-new Date(b.occurredAt)||String(a.createdAt||'').localeCompare(String(b.createdAt||'')));}
function deriveCash(){const f=finance(),rows=sortedTransactions();let balance=Number(f.settings.startingBalance)||0,lastTime=0;cashTimeMeta=new Map();const candles=[],metas=[];rows.forEach((t,i)=>{const open=balance,delta=t.direction==='inflow'?Math.abs(Number(t.amount)||0):-Math.abs(Number(t.amount)||0),close=open+delta,high=Math.max(open,close),low=Math.min(open,close);let time=Math.floor(new Date(t.occurredAt).getTime()/1000);if(!Number.isFinite(time))time=lastTime+1;if(time<=lastTime)time=lastTime+1;lastTime=time;const meta={...t,sequence:i+1,time,open,high,low,close,delta};cashTimeMeta.set(time,meta);metas.push(meta);candles.push({time,open,high,low,close});balance=close;});return{candles,balance,rows,metas};}
function ensureCashChart(){const host=$('#cashChart');if(!host||!window.LightweightCharts)return;if(cashChart)return;cashChart=LightweightCharts.createChart(host,{width:host.clientWidth,height:420,layout:{background:{type:'solid',color:'#0b0c10'},textColor:'#777985',fontFamily:'-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif',fontSize:10},grid:{vertLines:{color:'rgba(255,255,255,.025)'},horzLines:{color:'rgba(255,255,255,.035)'}},rightPriceScale:{borderColor:'#292a33',scaleMargins:{top:.12,bottom:.12}},timeScale:{borderColor:'#292a33',rightOffset:2,barSpacing:18,minBarSpacing:7,timeVisible:true,secondsVisible:false,tickMarkFormatter:time=>{const m=cashTimeMeta.get(Number(time));return m?`#${m.sequence}`:''}},crosshair:{mode:0,vertLine:{color:'rgba(0,217,255,.25)',labelBackgroundColor:'#171820'},horzLine:{color:'rgba(255,255,255,.12)',labelBackgroundColor:'#171820'}},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true,vertTouchDrag:false},handleScale:{mouseWheel:true,pinch:true,axisPressedMouseMove:true},localization:{priceFormatter:p=>money(p)}});cashSeries=cashChart.addSeries(LightweightCharts.CandlestickSeries,{upColor:finance().settings.cashUpColor,downColor:finance().settings.cashDownColor,borderVisible:false,wickUpColor:finance().settings.cashUpColor,wickDownColor:finance().settings.cashDownColor,priceLineVisible:false,lastValueVisible:true});cashChart.subscribeCrosshairMove(param=>{if(!param?.time){renderCashReadout();return;}const meta=cashTimeMeta.get(Number(param.time));renderCashReadout(meta)});cashResize=new ResizeObserver(()=>cashChart?.applyOptions({width:host.clientWidth}));cashResize.observe(host);}
function renderCashReadout(meta=null){const d=deriveCash(),latest=d.metas.at(-1)||null,replayMeta=replay.mode&&replay.position?replay.data[replay.position-1]:null,m=meta||replayMeta||(!replay.mode?latest:null);if(!m){$('#cashReadoutSeq').textContent=replay.mode?'REPLAY // STANDBY':'NO TRANSACTIONS';$('#cashReadoutState').textContent=replay.mode?'AWAITING PLAYBACK':'AWAITING CASHFLOW';$('#cashReadoutState').dataset.state='closed';$('#cashO').textContent=$('#cashH').textContent=$('#cashL').textContent=$('#cashC').textContent='—';$('#cashReadoutMeta').textContent=replay.mode?'PRESS PLAY OR MOVE THE SCRUBBER':'ADD A TRANSACTION TO START THE LEDGER';return;}$('#cashReadoutSeq').textContent=`TX #${m.sequence} // ${new Date(m.occurredAt).toLocaleString('en-SG',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false})}`;$('#cashReadoutState').textContent=m.direction==='inflow'?'INFLOW':'EXPENSE';$('#cashReadoutState').dataset.state=m.direction==='inflow'?'session':'missed';$('#cashO').textContent=money(m.open);$('#cashH').textContent=money(m.high);$('#cashL').textContent=money(m.low);$('#cashC').textContent=money(m.close);$('#cashReadoutMeta').textContent=`${(m.category||'OTHER').toUpperCase()} // ${m.description||'NO DESCRIPTION'} // ${m.delta>=0?'+':''}${money(m.delta)}`;}
function renderCashChart(reset=false){if(replay.mode){renderReplayFrame(reset);return;}const d=deriveCash();ensureCashChart();if(!cashSeries)return;const f=finance();cashSeries.applyOptions({upColor:f.settings.cashUpColor,downColor:f.settings.cashDownColor,wickUpColor:f.settings.cashUpColor,wickDownColor:f.settings.cashDownColor});cashSeries.setData(d.candles);if(reset||d.candles.length<=2)cashChart.timeScale().fitContent();renderCashReadout();}
function totals(){const f=finance(),inflow=f.transactions.filter(t=>t.direction==='inflow').reduce((s,t)=>s+Number(t.amount||0),0),expenses=f.transactions.filter(t=>t.direction==='expense').reduce((s,t)=>s+Number(t.amount||0),0),remaining=(Number(f.settings.startingBalance)||0)+inflow-expenses;return{inflow,expenses,remaining,count:f.transactions.length};}
function renderAllowanceMetrics(){if(replay.mode){const c=replay.position?replay.cumulative[replay.position-1]:null,balance=c?.balance??replay.startBalance;$('#cashRemainingLabel').textContent='REPLAY BALANCE';$('#cashStartingLabel').textContent='MONTH START';$('#cashInflowsLabel').textContent='INFLOWS PLAYED';$('#cashExpensesLabel').textContent='EXPENSES PLAYED';$('#cashTransactionCountLabel').textContent='TX POSITION';$('#cashRemaining').textContent=money(balance);$('#cashStarting').textContent=money(replay.startBalance);$('#cashInflows').textContent=money(c?.inflow||0);$('#cashExpenses').textContent=money(c?.expenses||0);$('#cashTransactionCount').textContent=`${replay.position} / ${replay.data.length}`;$('#cashRemaining').className=balance<0?'negative':'';return;}const t=totals();$('#cashRemainingLabel').textContent='REMAINING';$('#cashStartingLabel').textContent='STARTING ALLOWANCE';$('#cashInflowsLabel').textContent='INFLOWS';$('#cashExpensesLabel').textContent='EXPENSES';$('#cashTransactionCountLabel').textContent='TRANSACTIONS';$('#cashRemaining').textContent=money(t.remaining);$('#cashStarting').textContent=money(finance().settings.startingBalance);$('#cashInflows').textContent=money(t.inflow);$('#cashExpenses').textContent=money(t.expenses);$('#cashTransactionCount').textContent=String(t.count);$('#cashRemaining').className=t.remaining<0?'negative':'';}
function sgMonthKey(iso){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit'}).formatToParts(new Date(iso));const y=parts.find(x=>x.type==='year')?.value,m=parts.find(x=>x.type==='month')?.value;return y&&m?`${y}-${m}`:'';}
function previousMonthKey(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit'}).formatToParts(new Date());let y=Number(parts.find(x=>x.type==='year')?.value),m=Number(parts.find(x=>x.type==='month')?.value)-1;if(m===0){m=12;y--;}return `${y}-${String(m).padStart(2,'0')}`;}
function formatMonthKey(key){if(!/^\d{4}-\d{2}$/.test(key||''))return'—';const [y,m]=key.split('-').map(Number);return new Intl.DateTimeFormat('en-SG',{timeZone:'Asia/Singapore',month:'long',year:'numeric'}).format(new Date(Date.UTC(y,m-1,1)));}
function replayRate(){return replay.speed==='max'?null:2*Number(replay.speed||1);}
function stopReplay(complete=false){replay.playing=false;replay.lastTs=0;replay.carry=0;if(replay.raf){cancelAnimationFrame(replay.raf);replay.raf=0;}renderReplayControls(complete);}
function rebuildReplayData(preservePosition=true){const d=deriveCash(),prev=previousMonthKey(),keys=[...new Set(d.metas.map(m=>sgMonthKey(m.occurredAt)).filter(Boolean))];if(!keys.includes(prev))keys.push(prev);keys.sort();replay.months=keys;if(!replay.monthKey||!keys.includes(replay.monthKey))replay.monthKey=keys.includes(prev)?prev:(keys.at(-1)||prev);const before=d.metas.filter(m=>sgMonthKey(m.occurredAt)<replay.monthKey);replay.startBalance=before.length?before.at(-1).close:Number(finance().settings.startingBalance)||0;replay.data=d.metas.filter(m=>sgMonthKey(m.occurredAt)===replay.monthKey);let inflow=0,expenses=0;replay.cumulative=replay.data.map(m=>{if(m.direction==='inflow')inflow+=Math.abs(Number(m.amount)||0);else expenses+=Math.abs(Number(m.amount)||0);return{inflow,expenses,balance:m.close};});if(!preservePosition)replay.position=0;replay.position=Math.min(replay.position,replay.data.length);replay.rendered=-1;renderReplayMonthOptions();}
function renderReplayMonthOptions(){const sel=$('#replayMonthSelect');if(!sel)return;sel.innerHTML=replay.months.map(k=>`<option value="${k}">${formatMonthKey(k).toUpperCase()}</option>`).join('');sel.value=replay.monthKey;$('#replayMonthLabel').textContent=`${formatMonthKey(replay.monthKey).toUpperCase()} // ${replay.data.length} TRANSACTIONS`;const i=replay.months.indexOf(replay.monthKey);$('#replayPrevMonth').disabled=i<=0;$('#replayNextMonth').disabled=i<0||i>=replay.months.length-1;}
function renderReplayControls(complete=false){if(!replay.mode)return;const total=replay.data.length,pos=replay.position,rate=replayRate();$('#replayTxStatus').textContent=`TX ${pos} / ${total}`;$('#replayRate').textContent=replay.speed==='max'?'RATE // MAX FRAME BATCH':`RATE // ${rate<1?rate.toFixed(1):rate} TX/S`;const scrub=$('#replayScrubber');scrub.max=String(Math.max(total,1));scrub.value=String(pos);scrub.disabled=!total;$('#replayPlay').disabled=!total||replay.playing;$('#replayPause').disabled=!replay.playing;$('#replayStepBack').disabled=!total||pos===0;$('#replayStepForward').disabled=!total||pos>=total;$$('[data-replay-speed]').forEach(b=>b.classList.toggle('active',b.dataset.replaySpeed===replay.speed));const ticker=$('#replayTicker'),m=pos?replay.data[pos-1]:null;ticker.dataset.direction=m?.direction||'';if(m){ticker.innerHTML=`<span>${complete&&pos===total?'REPLAY COMPLETE':`TX #${m.sequence}`}</span><b>${esc((m.description||m.category||'TRANSACTION').toUpperCase())} // ${m.delta>=0?'+':'−'}${money(Math.abs(m.delta))} // BAL ${money(m.close)}</b>`;}else{ticker.innerHTML=`<span>${total?'STANDBY':'NO DATA'}</span><b>${total?'SELECT PLAY TO RECONSTRUCT CASHFLOW':'NO TRANSACTIONS RECORDED FOR THIS MONTH'}</b>`;}}
function renderReplayFrame(fit=false){ensureCashChart();if(!cashSeries)return;if(!replay.data.length&&replay.mode)rebuildReplayData(true);const f=finance();cashSeries.applyOptions({upColor:f.settings.cashUpColor,downColor:f.settings.cashDownColor,wickUpColor:f.settings.cashUpColor,wickDownColor:f.settings.cashDownColor});const pos=Math.max(0,Math.min(replay.position,replay.data.length));if(replay.rendered<0||pos<replay.rendered||pos-replay.rendered>160){cashSeries.setData(replay.data.slice(0,pos).map(m=>({time:m.time,open:m.open,high:m.high,low:m.low,close:m.close})));}else if(pos>replay.rendered){for(let i=replay.rendered;i<pos;i++){const m=replay.data[i];cashSeries.update({time:m.time,open:m.open,high:m.high,low:m.low,close:m.close});}}replay.rendered=pos;if(fit||pos<=2)cashChart.timeScale().fitContent();else if(pos)cashChart.timeScale().scrollToPosition(0,false);renderAllowanceMetrics();renderCashReadout();renderReplayControls(false);}
function setReplayPosition(next,fit=false){replay.position=Math.max(0,Math.min(Number(next)||0,replay.data.length));renderReplayFrame(fit);}
function enterReplay(){if(replay.mode)return;replay.mode=true;replay.position=0;replay.rendered=-1;rebuildReplayData(false);$('#cashReplayPanel').classList.remove('hidden');$('.cash-panel')?.classList.add('replay-active');$('#cashReplayBtn').classList.add('active-mode');$('#cashLiveBtn').classList.remove('active-mode');renderReplayFrame(true);}
function exitReplay(fit=true){stopReplay(false);replay.mode=false;$('#cashReplayPanel').classList.add('hidden');$('.cash-panel')?.classList.remove('replay-active');$('#cashReplayBtn').classList.remove('active-mode');$('#cashLiveBtn').classList.add('active-mode');replay.rendered=-1;renderAllowanceMetrics();renderCashChart(fit);}
function setReplayMonth(key){stopReplay(false);replay.monthKey=key;replay.position=0;replay.rendered=-1;rebuildReplayData(false);renderReplayFrame(true);}
function shiftReplayMonth(delta){const i=replay.months.indexOf(replay.monthKey),n=i+delta;if(n>=0&&n<replay.months.length)setReplayMonth(replay.months[n]);}
function replayTick(ts){if(!replay.playing)return;const total=replay.data.length;if(replay.position>=total){stopReplay(true);return;}if(!replay.lastTs)replay.lastTs=ts;const dt=Math.min(.25,Math.max(0,(ts-replay.lastTs)/1000));replay.lastTs=ts;let steps=0;if(replay.speed==='max'){steps=Math.min(128,total-replay.position);}else{replay.carry+=dt*replayRate();steps=Math.floor(replay.carry);if(steps>0)replay.carry-=steps;}if(steps>0)setReplayPosition(replay.position+steps,false);if(replay.position>=total){stopReplay(true);return;}replay.raf=requestAnimationFrame(replayTick);}
function playReplay(){if(!replay.mode)enterReplay();if(!replay.data.length)return toast('NO TRANSACTIONS IN SELECTED REPLAY MONTH',true);if(replay.position>=replay.data.length){replay.position=0;replay.rendered=-1;cashSeries?.setData([]);}replay.playing=true;replay.lastTs=0;replay.carry=0;renderReplayControls(false);replay.raf=requestAnimationFrame(replayTick);}
function pauseReplay(){stopReplay(false);}
function resetReplay(){stopReplay(false);replay.position=0;replay.rendered=-1;renderReplayFrame(true);}
function stepReplay(delta){stopReplay(false);setReplayPosition(replay.position+delta,false);}
function setReplaySpeed(v){replay.speed=String(v);replay.carry=0;replay.lastTs=0;renderReplayControls(false);}

function renderTransactions(){const items=[...finance().transactions].sort((a,b)=>new Date(b.occurredAt)-new Date(a.occurredAt)),pages=Math.max(1,Math.ceil(items.length/TX_PAGE_SIZE));txPage=Math.min(txPage,pages-1);const from=txPage*TX_PAGE_SIZE,part=items.slice(from,from+TX_PAGE_SIZE),host=$('#cashRecords');host.innerHTML=part.length?part.map(t=>`<button class="cash-record" data-tx="${t.id}"><span><b>${esc(t.description||t.category||'TRANSACTION')}</b><small>${new Date(t.occurredAt).toLocaleString('en-SG',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false})}</small></span><span>${esc((t.category||'OTHER').toUpperCase())}</span><strong class="${t.direction==='inflow'?'positive':'negative'}">${t.direction==='inflow'?'+':'−'}${money(t.amount)}</strong><i>›</i></button>`).join(''):'<div class="finance-empty">NO CASH TRANSACTIONS RECORDED</div>';$('#cashPager').textContent=items.length?`${from+1}–${Math.min(from+TX_PAGE_SIZE,items.length)} OF ${items.length}`:'0 RECORDS';$('#cashPrevPage').disabled=txPage===0;$('#cashNextPage').disabled=txPage>=pages-1;host.querySelectorAll('[data-tx]').forEach(b=>b.onclick=()=>openTransaction(b.dataset.tx));}
function positionMetrics(){const f=finance();let cost=0,market=0,pnl=0,exposure=0;for(const p of f.positions){const qty=Number(p.quantity)||0,entry=Number(p.entryPrice)||0,current=p.currentPrice==null?entry:Number(p.currentPrice)||0;cost+=qty*entry;market+=qty*current;pnl+=(current-entry)*qty;exposure+=Math.abs(qty*current);}const equity=(Number(f.settings.portfolioCash)||0)+market;return{cost,market,pnl,exposure,equity,cash:Number(f.settings.portfolioCash)||0,pnlPct:Math.abs(cost)>0?pnl/Math.abs(cost)*100:0};}
function renderPortfolio(){const m=positionMetrics();$('#portfolioEquity').textContent=money(m.equity);$('#portfolioCash').textContent=money(m.cash);$('#portfolioMarket').textContent=money(m.market);$('#portfolioPnl').textContent=money(m.pnl);$('#portfolioPnl').className=m.pnl>=0?'positive':'negative';$('#portfolioPnlPct').textContent=pct(m.pnlPct);$('#portfolioPnlPct').className=m.pnlPct>=0?'positive':'negative';$('#portfolioExposure').textContent=money(m.exposure);const host=$('#positionList'),items=[...finance().positions].sort((a,b)=>a.symbol.localeCompare(b.symbol));host.innerHTML=items.length?items.map(p=>{const q=Number(p.quantity)||0,e=Number(p.entryPrice)||0,c=p.currentPrice==null?e:Number(p.currentPrice)||0,mv=q*c,pnl=(c-e)*q,pp=Math.abs(q*e)>0?pnl/Math.abs(q*e)*100:0;return`<button class="position-row" data-position="${p.id}"><span class="position-symbol"><b>${esc(p.symbol)}</b><small>${esc((p.assetType||'ASSET').toUpperCase())}${p.sector?` // ${esc(p.sector.toUpperCase())}`:''}</small></span><span><small>QTY</small><b>${q.toLocaleString()}</b></span><span><small>ENTRY</small><b>${money(e)}</b></span><span><small>CURRENT</small><b>${money(c)}</b></span><span><small>VALUE</small><b>${money(mv)}</b></span><span class="${pnl>=0?'positive':'negative'}"><small>P&amp;L</small><b>${money(pnl)} // ${pct(pp)}</b></span><i>›</i></button>`}).join(''):'<div class="finance-empty">NO PORTFOLIO POSITIONS</div>';host.querySelectorAll('[data-position]').forEach(b=>b.onclick=()=>openPosition(b.dataset.position));}
function renderJournal(){const items=[...finance().journal].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)),pages=Math.max(1,Math.ceil(items.length/JOURNAL_PAGE_SIZE));journalPage=Math.min(journalPage,pages-1);const from=journalPage*JOURNAL_PAGE_SIZE,part=items.slice(from,from+JOURNAL_PAGE_SIZE),host=$('#journalList');host.innerHTML=part.length?part.map(j=>`<button class="journal-row" data-journal="${j.id}"><span>${new Date(j.createdAt).toLocaleString('en-SG',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})}</span><p>${esc(j.body)}</p><i>›</i></button>`).join(''):'<div class="finance-empty">NO JOURNAL ENTRIES</div>';$('#journalPager').textContent=items.length?`${from+1}–${Math.min(from+JOURNAL_PAGE_SIZE,items.length)} OF ${items.length}`:'0 RECORDS';$('#journalPrevPage').disabled=journalPage===0;$('#journalNextPage').disabled=journalPage>=pages-1;host.querySelectorAll('[data-journal]').forEach(b=>b.onclick=()=>openJournal(b.dataset.journal));}
export function renderFinance(){finance();if(replay.mode)rebuildReplayData(true);renderAllowanceMetrics();renderCashChart();renderTransactions();renderPortfolio();renderJournal();}
function openTransaction(id=null){if(replay.mode)exitReplay(false);const t=id?finance().transactions.find(x=>x.id===id):null;$('#transactionId').value=t?.id||'';$('#transactionModalTitle').textContent=t?'Edit Transaction':'New Transaction';$('#transactionOccurredAt').value=localInput(t?.occurredAt||new Date().toISOString());$('#transactionDirection').value=t?.direction||'expense';$('#transactionAmount').value=t?.amount??'';$('#transactionCategory').value=t?.category||'Food';$('#transactionDescription').value=t?.description||'';$('#transactionNotes').value=t?.notes||'';$('#deleteTransactionBtn').classList.toggle('hidden',!t);$('#transactionDialog').showModal();}
function openFinanceSettings(){const s=finance().settings;$('#financeCurrency').value=s.currency||'SGD';$('#financeStartingBalance').value=s.startingBalance??0;$('#financePortfolioCash').value=s.portfolioCash??0;$('#cashUpColor').value=s.cashUpColor||'#2fd69a';$('#cashDownColor').value=s.cashDownColor||'#ff405c';$('#financeSettingsDialog').showModal();}
function openPosition(id=null){const p=id?finance().positions.find(x=>x.id===id):null;$('#positionId').value=p?.id||'';$('#positionModalTitle').textContent=p?'Edit Position':'New Position';$('#positionSymbol').value=p?.symbol||'';$('#positionAssetType').value=p?.assetType||'EQUITY';$('#positionQuantity').value=p?.quantity??'';$('#positionEntryPrice').value=p?.entryPrice??'';$('#positionCurrentPrice').value=p?.currentPrice??'';$('#positionSector').value=p?.sector||'';$('#positionNotes').value=p?.notes||'';$('#deletePositionBtn').classList.toggle('hidden',!p);$('#positionDialog').showModal();}
function openJournal(id=null){const j=id?finance().journal.find(x=>x.id===id):null;$('#journalId').value=j?.id||'';$('#journalModalTitle').textContent=j?'Edit Journal Entry':'New Journal Entry';$('#journalBody').value=j?.body||'';$('#deleteJournalBtn').classList.toggle('hidden',!j);$('#journalDialog').showModal();}
async function saveTransaction(e){e.preventDefault();const id=$('#transactionId').value,when=new Date($('#transactionOccurredAt').value);if(!Number.isFinite(when.getTime()))return toast('INVALID TRANSACTION TIME',true);if(when.getTime()>Date.now()+60000)return toast('TRANSACTIONS CANNOT BE FUTURE-DATED',true);const payload={occurredAt:when.toISOString(),direction:$('#transactionDirection').value,amount:Number($('#transactionAmount').value),category:$('#transactionCategory').value,description:$('#transactionDescription').value,notes:$('#transactionNotes').value};try{const r=await api(id?`/api/v8/finance/transactions/${encodeURIComponent(id)}`:'/api/v8/finance/transactions',{method:id?'PATCH':'POST',body:payload});upsert(finance().transactions,r.item);$('#transactionDialog').close();txPage=0;renderFinance();toast('TRANSACTION SAVED');}catch(err){toast(err.message,true)}}
async function deleteTransaction(){const id=$('#transactionId').value;if(!id||!confirm('Delete this cash transaction?'))return;const btn=$('#deleteTransactionBtn');btn.disabled=true;try{await api(`/api/v8/finance/transactions/${encodeURIComponent(id)}`,{method:'DELETE'});remove(finance().transactions,id);$('#transactionDialog').close();renderFinance();toast('TRANSACTION DELETED');}catch(err){toast(err.message,true)}finally{btn.disabled=false}}
async function saveFinanceSettings(e){e.preventDefault();const payload={currency:$('#financeCurrency').value,startingBalance:Number($('#financeStartingBalance').value)||0,portfolioCash:Number($('#financePortfolioCash').value)||0,cashUpColor:$('#cashUpColor').value,cashDownColor:$('#cashDownColor').value};try{const r=await api('/api/v8/finance/settings',{method:'PATCH',body:payload});finance().settings=r.item;$('#financeSettingsDialog').close();renderFinance();cashChart?.timeScale().fitContent();toast('FINANCE SETTINGS SAVED');}catch(err){toast(err.message,true)}}
async function savePosition(e){e.preventDefault();const id=$('#positionId').value,payload={symbol:$('#positionSymbol').value,assetType:$('#positionAssetType').value,quantity:Number($('#positionQuantity').value),entryPrice:Number($('#positionEntryPrice').value),currentPrice:$('#positionCurrentPrice').value===''?null:Number($('#positionCurrentPrice').value),sector:$('#positionSector').value,notes:$('#positionNotes').value};try{const r=await api(id?`/api/v8/finance/positions/${encodeURIComponent(id)}`:'/api/v8/finance/positions',{method:id?'PATCH':'POST',body:payload});upsert(finance().positions,r.item);$('#positionDialog').close();renderPortfolio();toast('POSITION SAVED');}catch(err){toast(err.message,true)}}
async function deletePosition(){const id=$('#positionId').value;if(!id||!confirm('Delete this portfolio position?'))return;const btn=$('#deletePositionBtn');btn.disabled=true;try{await api(`/api/v8/finance/positions/${encodeURIComponent(id)}`,{method:'DELETE'});remove(finance().positions,id);$('#positionDialog').close();renderPortfolio();toast('POSITION DELETED');}catch(err){toast(err.message,true)}finally{btn.disabled=false}}
async function saveJournal(e){e.preventDefault();const id=$('#journalId').value,payload={body:$('#journalBody').value};try{const r=await api(id?`/api/v8/finance/journal/${encodeURIComponent(id)}`:'/api/v8/finance/journal',{method:id?'PATCH':'POST',body:payload});upsert(finance().journal,r.item);$('#journalDialog').close();journalPage=0;renderJournal();toast('JOURNAL SAVED');}catch(err){toast(err.message,true)}}
async function deleteJournal(){const id=$('#journalId').value;if(!id||!confirm('Delete this finance journal entry?'))return;const btn=$('#deleteJournalBtn');btn.disabled=true;try{await api(`/api/v8/finance/journal/${encodeURIComponent(id)}`,{method:'DELETE'});remove(finance().journal,id);$('#journalDialog').close();renderJournal();toast('JOURNAL DELETED');}catch(err){toast(err.message,true)}finally{btn.disabled=false}}
function exportCashCsv(){const rows=[['sequence','occurred_at','direction','amount','category','description','notes','balance_after']],d=deriveCash();for(const [time,m] of cashTimeMeta)rows.push([m.sequence,m.occurredAt,m.direction,m.amount,m.category,m.description,m.notes,m.close]);const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='neon-ops-cashflow.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}

export function initFinance(toastFn){toast=toastFn;finance();$('#newTransactionBtn').onclick=()=>openTransaction();$('#financeSettingsBtn').onclick=openFinanceSettings;$('#cashLiveBtn').onclick=()=>exitReplay(true);$('#cashReplayBtn').onclick=enterReplay;$('#cashExportBtn').onclick=exportCashCsv;$('#replayPlay').onclick=playReplay;$('#replayPause').onclick=pauseReplay;$('#replayReset').onclick=resetReplay;$('#replayStepBack').onclick=()=>stepReplay(-1);$('#replayStepForward').onclick=()=>stepReplay(1);$('#replayPrevMonth').onclick=()=>shiftReplayMonth(-1);$('#replayNextMonth').onclick=()=>shiftReplayMonth(1);$('#replayMonthSelect').onchange=e=>setReplayMonth(e.target.value);$('#replayScrubber').oninput=e=>{stopReplay(false);setReplayPosition(Number(e.target.value),false)};$$('[data-replay-speed]').forEach(b=>b.onclick=()=>setReplaySpeed(b.dataset.replaySpeed));$('#transactionForm').onsubmit=saveTransaction;$('#deleteTransactionBtn').onclick=deleteTransaction;$('#financeSettingsForm').onsubmit=saveFinanceSettings;$('#newPositionBtn').onclick=()=>openPosition();$('#positionForm').onsubmit=savePosition;$('#deletePositionBtn').onclick=deletePosition;$('#newJournalBtn').onclick=()=>openJournal();$('#journalForm').onsubmit=saveJournal;$('#deleteJournalBtn').onclick=deleteJournal;$('#cashPrevPage').onclick=()=>{if(txPage>0){txPage--;renderTransactions()}};$('#cashNextPage').onclick=()=>{const pages=Math.ceil(finance().transactions.length/TX_PAGE_SIZE);if(txPage+1<pages){txPage++;renderTransactions()}};$('#journalPrevPage').onclick=()=>{if(journalPage>0){journalPage--;renderJournal()}};$('#journalNextPage').onclick=()=>{const pages=Math.ceil(finance().journal.length/JOURNAL_PAGE_SIZE);if(journalPage+1<pages){journalPage++;renderJournal()}};renderFinance();}
export function refreshFinance(){if(cashChart)cashChart.applyOptions({width:$('#cashChart')?.clientWidth||600});renderFinance();}
