import { api } from './api.js';
import { state,upsert,remove } from './state.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let chart=null,series=null,activeMovementId=null,page=0,toast=()=>{},chartData=[];
const PAGE_SIZE=10;
const clamp=(n,a,b)=>Math.min(Math.max(Number(n)||0,a),b);
const dayKey=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(d));
const addDay=(key,n=1)=>{const d=new Date(key+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
const isoDow=key=>{const d=new Date(key+'T00:00:00Z').getUTCDay();return d===0?7:d};
const today=()=>dayKey(new Date());
const currentMovement=()=>state.fitness.movements.find(m=>m.id===activeMovementId)||state.fitness.movements[0]||null;
const movementSessions=m=>state.fitness.sessions.filter(s=>s.movementId===m.id).sort((a,b)=>new Date(a.performedAt)-new Date(b.performedAt));
function metricsOf(sessions){let volume=0,e1rm=0,sets=0;for(const s of sessions)for(const x of s.sets||[]){const w=Number(x.weightKg)||0,r=Number(x.reps)||0;volume+=w*r;sets++;if(w&&r)e1rm=Math.max(e1rm,w*(1+r/30));}return{volume,e1rm,sets};}
function deriveCandles(m){const ss=movementSessions(m),byDay={};for(const s of ss)(byDay[dayKey(s.performedAt)]??=[]).push(s);const first=ss[0]?dayKey(ss[0].performedAt):dayKey(m.createdAt||new Date()),start=first<dayKey(m.createdAt||new Date())?first:dayKey(m.createdAt||new Date()),end=today();let close=100,missed=0;const out=[],detail=[];let baseVol=Number(m.baselineVolume)||0,baseE=Number(m.baselineE1rm)||0;if((!baseVol||!baseE)&&ss.length){const fm=metricsOf(byDay[first]||[ss[0]]);if(!baseVol)baseVol=fm.volume||1;if(!baseE)baseE=fm.e1rm||1;}
for(let k=start;k<=end;k=addDay(k)){const daySessions=byDay[k]||[],scheduled=(m.scheduledDays||[]).map(Number).includes(isoDow(k)),open=close;if(daySessions.length){const met=metricsOf(daySessions),ratios=[];if(baseVol&&met.volume)ratios.push(met.volume/baseVol);if(baseE&&met.e1rm)ratios.push(met.e1rm/baseE);const ratio=ratios.length?ratios.reduce((a,b)=>a+b,0)/ratios.length:1;const gain=clamp(.004+(ratio-1)*.03,.001,.025);close=open*(1+gain);missed=0;out.push({time:k,open:+open.toFixed(3),high:+(Math.max(open,close)*1.003).toFixed(3),low:+(Math.min(open,close)*.998).toFixed(3),close:+close.toFixed(3)});detail.push({time:k,state:'session',close,metrics:met});}
else if(scheduled){missed+=1;const decay=Math.min(Number(m.decayMax)||.02,(Number(m.decayBase)||.005)+(Number(m.decayAcceleration)||.0015)*missed);close=open*(1-decay);out.push({time:k,open:+open.toFixed(3),high:+(open*1.001).toFixed(3),low:+(close*.997).toFixed(3),close:+close.toFixed(3)});detail.push({time:k,state:'missed',close,decay,missed});}
else{out.push({time:k});detail.push({time:k,state:'closed',close});}}
return{data:out,detail,last:close,missed,baseVol,baseE};}
function ensureChart(){const el=$('#fitnessChart');if(!el||chart)return;const L=window.LightweightCharts;if(!L){el.innerHTML='<div class="fitness-empty">CHART ENGINE FAILED TO LOAD</div>';return;}chart=L.createChart(el,{autoSize:true,layout:{background:{type:'solid',color:'transparent'},textColor:'#8f909a',fontFamily:'Arial, Helvetica, sans-serif'},grid:{vertLines:{color:'rgba(255,255,255,.035)'},horzLines:{color:'rgba(255,255,255,.045)'}},rightPriceScale:{borderColor:'#2b2c35',scaleMargins:{top:.12,bottom:.12}},timeScale:{borderColor:'#2b2c35',timeVisible:false,rightOffset:3,barSpacing:10,minBarSpacing:3,fixLeftEdge:false,fixRightEdge:false},crosshair:{vertLine:{color:'rgba(0,217,255,.32)',labelBackgroundColor:'#151820'},horzLine:{color:'rgba(0,217,255,.22)',labelBackgroundColor:'#151820'}},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true,vertTouchDrag:false},handleScale:{axisPressedMouseMove:true,mouseWheel:true,pinch:true}});series=chart.addSeries(L.CandlestickSeries,{upColor:'#2fd69a',downColor:'#ff405c',borderUpColor:'#2fd69a',borderDownColor:'#ff405c',wickUpColor:'#69e7bd',wickDownColor:'#ff7184',priceLineVisible:false,lastValueVisible:true});}
function setRange(range){if(!chart||!chartData.length)return;const valid=chartData.filter(x=>x.open!==undefined);if(!valid.length)return;if(range==='ALL'){chart.timeScale().fitContent();return;}const days={1:31,3:92,6:184,12:366}[range]||92;const to=valid[valid.length-1].time,from=addDay(to,-days);chart.timeScale().setVisibleRange({from,to});}
function renderMovementSelect(){const sel=$('#movementSelect');sel.innerHTML=state.fitness.movements.map(m=>`<option value="${m.id}">${escapeHtml(m.symbol||'MOV')} // ${escapeHtml(m.name)}</option>`).join('');if(!activeMovementId&&state.fitness.movements[0])activeMovementId=state.fitness.movements[0].id;if(activeMovementId)sel.value=activeMovementId;}
function renderFitness(){renderMovementSelect();const m=currentMovement();const empty=$('#fitnessEmpty'),body=$('#fitnessBody');if(!m){empty.classList.remove('hidden');body.classList.add('hidden');renderRecords();return;}empty.classList.add('hidden');body.classList.remove('hidden');ensureChart();const d=deriveCandles(m);chartData=d.data;series?.setData(chartData);setTimeout(()=>setRange($('#fitnessRanges .active')?.dataset.range||'3'),0);$('#fitnessIndex').textContent=d.last.toFixed(2);$('#fitnessMissed').textContent=String(d.missed);const ss=movementSessions(m),weekAgo=Date.now()-7*86400000;$('#fitnessWeekSessions').textContent=ss.filter(s=>new Date(s.performedAt).getTime()>=weekAgo).length;const met=metricsOf(ss);$('#fitnessBestE1rm').textContent=met.e1rm?met.e1rm.toFixed(1)+' kg':'—';$('#fitnessSymbol').textContent=m.symbol||'MOV';$('#fitnessSchedule').textContent=(m.scheduledDays||[]).length?`SCHEDULE // ${(m.scheduledDays||[]).map(x=>['','MON','TUE','WED','THU','FRI','SAT','SUN'][x]).join(' ')}`:'SCHEDULE // NONE';renderRecords();}
function renderRecords(){const m=currentMovement(),host=$('#fitnessRecords');if(!m){host.innerHTML='<div class="fitness-empty">CREATE A MOVEMENT TO BEGIN.</div>';$('#fitnessPager').textContent='0 / 0';return;}const items=movementSessions(m).slice().reverse(),pages=Math.max(1,Math.ceil(items.length/PAGE_SIZE));page=Math.min(page,pages-1);const chunk=items.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE);host.innerHTML=chunk.map(s=>{const met=metricsOf([s]);return `<button class="fitness-record" data-session="${s.id}"><span><b>${dayKey(s.performedAt)}</b><small>${new Date(s.performedAt).toLocaleTimeString('en-SG',{hour:'2-digit',minute:'2-digit'})}</small></span><span>${s.sets?.length||0} SETS</span><span>${met.volume.toFixed(0)} KG·REP</span><span>${met.e1rm?met.e1rm.toFixed(1)+' E1RM':'—'}</span><i>›</i></button>`}).join('')||'<div class="fitness-empty">NO COMPLETED SESSIONS.</div>';$('#fitnessPager').textContent=`${page+1} / ${pages}`;host.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>openSession(b.dataset.session));}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function localInput(iso){if(!iso)return'';const d=new Date(iso),pad=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function openMovement(id=null){const m=id?state.fitness.movements.find(x=>x.id===id):null;$('#movementId').value=m?.id||'';$('#movementModalTitle').textContent=m?'Edit Movement':'New Movement';$('#movementName').value=m?.name||'';$('#movementSymbol').value=m?.symbol||'';$('#movementBaselineVolume').value=m?.baselineVolume||'';$('#movementBaselineE1rm').value=m?.baselineE1rm||'';$('#decayBase').value=(Number(m?.decayBase??.005)*100).toFixed(2);$('#decayAcceleration').value=(Number(m?.decayAcceleration??.0015)*100).toFixed(2);$('#decayMax').value=(Number(m?.decayMax??.02)*100).toFixed(2);$$('#movementDays button').forEach(b=>b.classList.toggle('active',(m?.scheduledDays||[]).map(Number).includes(Number(b.dataset.day))));$('#deleteMovementBtn').classList.toggle('hidden',!m);$('#movementDialog').showModal();}
function addSetRow(s={}){const row=document.createElement('div');row.className='set-row';row.innerHTML=`<span class="set-no"></span><input class="set-weight" type="number" min="0" step="0.25" placeholder="KG" value="${s.weightKg??''}"><input class="set-reps" type="number" min="0" step="1" placeholder="REPS" value="${s.reps??''}"><input class="set-rpe" type="number" min="0" max="10" step="0.5" placeholder="RPE" value="${s.rpe??''}"><button type="button" class="set-remove">×</button>`;row.querySelector('.set-remove').onclick=()=>{row.remove();renumberSets()};$('#setRows').appendChild(row);renumberSets();}
function renumberSets(){$$('#setRows .set-row').forEach((r,i)=>r.querySelector('.set-no').textContent=String(i+1).padStart(2,'0'));}
function openSession(id=null){const s=id?state.fitness.sessions.find(x=>x.id===id):null,m=currentMovement();if(!m)return;$('#sessionId').value=s?.id||'';$('#sessionModalTitle').textContent=s?'Edit Session':'Log Session';$('#sessionMovementName').textContent=`${m.symbol||'MOV'} // ${m.name}`;$('#sessionPerformedAt').value=localInput(s?.performedAt||new Date().toISOString());$('#sessionBodyWeight').value=s?.bodyWeightKg??'';$('#sessionNotes').value=s?.notes||'';$('#setRows').innerHTML='';(s?.sets?.length?s.sets:[{}, {}, {}]).forEach(addSetRow);$('#deleteSessionBtn').classList.toggle('hidden',!s);$('#sessionDialog').showModal();}
async function saveMovement(e){e.preventDefault();const id=$('#movementId').value,scheduledDays=$$('#movementDays button.active').map(b=>Number(b.dataset.day)),payload={name:$('#movementName').value,symbol:$('#movementSymbol').value,baselineVolume:Number($('#movementBaselineVolume').value)||0,baselineE1rm:Number($('#movementBaselineE1rm').value)||0,scheduledDays,decayBase:Number($('#decayBase').value)/100,decayAcceleration:Number($('#decayAcceleration').value)/100,decayMax:Number($('#decayMax').value)/100,exerciseType:'strength',model:'hybrid'};try{const r=await api(id?`/api/v8/fitness/movements/${encodeURIComponent(id)}`:'/api/v8/fitness/movements',{method:id?'PATCH':'POST',body:payload});upsert(state.fitness.movements,r.item);activeMovementId=r.item.id;$('#movementDialog').close();page=0;renderFitness();toast('MOVEMENT SAVED');}catch(err){toast(err.message,true)}}
async function saveSession(e){e.preventDefault();const id=$('#sessionId').value,m=currentMovement(),sets=$$('#setRows .set-row').map(r=>({weightKg:Number(r.querySelector('.set-weight').value)||0,reps:Number(r.querySelector('.set-reps').value)||0,rpe:r.querySelector('.set-rpe').value===''?null:Number(r.querySelector('.set-rpe').value)}));try{const r=await api(id?`/api/v8/fitness/sessions/${encodeURIComponent(id)}`:'/api/v8/fitness/sessions',{method:id?'PATCH':'POST',body:{movementId:m.id,performedAt:new Date($('#sessionPerformedAt').value).toISOString(),exerciseType:'strength',bodyWeightKg:$('#sessionBodyWeight').value,notes:$('#sessionNotes').value,sets}});upsert(state.fitness.sessions,r.item);$('#sessionDialog').close();renderFitness();toast('SESSION SAVED');}catch(err){toast(err.message,true)}}
async function deleteSession(){const id=$('#sessionId').value;if(!id||!confirm('Delete this completed training session?'))return;const btn=$('#deleteSessionBtn');btn.disabled=true;try{await api(`/api/v8/fitness/sessions/${encodeURIComponent(id)}`,{method:'DELETE'});remove(state.fitness.sessions,id);$('#sessionDialog').close();renderFitness();toast('SESSION DELETED');}catch(err){toast(err.message,true)}finally{btn.disabled=false}}
async function deleteMovement(){const id=$('#movementId').value;if(!id||!confirm('Delete this movement and all of its sessions?'))return;const btn=$('#deleteMovementBtn');btn.disabled=true;try{await api(`/api/v8/fitness/movements/${encodeURIComponent(id)}`,{method:'DELETE'});state.fitness.movements=state.fitness.movements.filter(x=>x.id!==id);state.fitness.sessions=state.fitness.sessions.filter(x=>x.movementId!==id);activeMovementId=state.fitness.movements[0]?.id||null;$('#movementDialog').close();renderFitness();toast('MOVEMENT DELETED');}catch(err){toast(err.message,true)}finally{btn.disabled=false}}
export function initFitness(toastFn){toast=toastFn;$('#movementSelect').onchange=e=>{activeMovementId=e.target.value;page=0;renderFitness()};$('#newMovementBtn').onclick=()=>openMovement();$('#editMovementBtn').onclick=()=>currentMovement()&&openMovement(currentMovement().id);$('#logSessionBtn').onclick=()=>openSession();$('#movementForm').onsubmit=saveMovement;$('#sessionForm').onsubmit=saveSession;$('#deleteSessionBtn').onclick=deleteSession;$('#deleteMovementBtn').onclick=deleteMovement;$('#addSetBtn').onclick=()=>addSetRow();$$('#movementDays button').forEach(b=>b.onclick=()=>b.classList.toggle('active'));$$('#fitnessRanges button').forEach(b=>b.onclick=()=>{$$('#fitnessRanges button').forEach(x=>x.classList.remove('active'));b.classList.add('active');setRange(b.dataset.range)});$('#fitnessReset').onclick=()=>setRange('3');$('#fitnessPrevPage').onclick=()=>{if(page>0){page--;renderRecords()}};$('#fitnessNextPage').onclick=()=>{const m=currentMovement(),pages=Math.ceil(movementSessions(m).length/PAGE_SIZE);if(page+1<pages){page++;renderRecords()}};renderFitness();}
export function refreshFitness(){renderFitness();}
