import { api,API_BASE } from './api.js';
import { state } from './state.js';

const $=s=>document.querySelector(s);
let toast=()=>{},refreshTimer=null,progressTimer=null,lastPaintAt=0,seekBusy=false;
const connected=()=>!!state.integrations?.spotify;
const fmtMs=ms=>{ms=Math.max(0,Number(ms)||0);const s=Math.floor(ms/1000),m=Math.floor(s/60);return `${m}:${String(s%60).padStart(2,'0')}`;};
const artOf=t=>t?.album?.images?.[0]?.url||null;
const artistOf=t=>(t?.artists||[]).map(a=>a.name).join(', ')||'—';
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function img(url,alt=''){return url?`<img src="${escapeHtml(url)}" alt="${escapeHtml(alt)}" loading="lazy">`:`<div class="media-thumb-fallback">SP</div>`;}
function spotifyConnect(){location.assign(`${API_BASE}/auth/spotify?returnTo=${encodeURIComponent(location.href.split('#')[0])}`);}

export function initMedia(t){toast=t;$('#spotifyConnectBtn').onclick=spotifyConnect;$('#spotifyRefreshBtn').onclick=()=>refreshMedia(true);$('#spotifyDisconnectBtn').onclick=disconnect;
  $('#spotifyPrev').onclick=()=>action('previous');$('#spotifyNext').onclick=()=>action('next');$('#spotifyPlayPause').onclick=()=>action(state.media?.overview?.playback?.isPlaying?'pause':'play');
  $('#spotifyShuffle').onclick=()=>action('shuffle',{state:!state.media?.overview?.playback?.shuffleState});
  $('#spotifyRepeat').onclick=()=>{const x=state.media?.overview?.playback?.repeatState||'off',n=x==='off'?'context':x==='context'?'track':'off';action('repeat',{state:n});};
  $('#spotifyDevice').onchange=e=>{if(e.target.value)action('transfer',{deviceId:e.target.value,play:!!state.media?.overview?.playback?.isPlaying});};
  $('#spotifyVolume').oninput=e=>$('#spotifyVolumeValue').textContent=`${e.target.value}%`;$('#spotifyVolume').onchange=e=>action('volume',{volumePercent:Number(e.target.value),deviceId:$('#spotifyDevice').value||undefined});
  $('#spotifyProgress').oninput=()=>{seekBusy=true;paintProgress(Number($('#spotifyProgress').value));};$('#spotifyProgress').onchange=e=>{const p=state.media?.overview?.playback,item=p?.item;if(!item?.durationMs)return;const ms=Math.round(Number(e.target.value)/1000*item.durationMs);seekBusy=false;action('seek',{positionMs:ms,deviceId:$('#spotifyDevice').value||undefined});};
  if(!progressTimer)progressTimer=setInterval(tickProgress,500);if(!refreshTimer)refreshTimer=setInterval(()=>{if(document.querySelector('#pageMedia')?.classList.contains('active'))refreshMedia(false);},15000);renderShell();}

export async function refreshMedia(showToast=false){renderShell();if(!connected()){state.media={overview:null,loaded:true};render();return;}
  const btn=$('#spotifyRefreshBtn');if(btn)btn.disabled=true;try{const o=await api('/api/v8/spotify/overview');state.media={overview:o,loaded:true};lastPaintAt=Date.now();render();if(showToast)toast('SPOTIFY REFRESHED');}catch(e){renderError(e.message);if(showToast)toast(e.message,true);}finally{if(btn)btn.disabled=false;}}

function renderShell(){const c=connected();$('#spotifyStatus').textContent=c?'CONNECTED':'NOT CONNECTED';$('#spotifyStatus').dataset.state=c?'success':'warning';$('#spotifyConnectBtn').classList.toggle('hidden',c);$('#spotifyDisconnectBtn').classList.toggle('hidden',!c);$('#spotifyRefreshBtn').disabled=!c;$('#spotifyDisconnected').classList.toggle('hidden',c);$('#spotifyConnected').classList.toggle('hidden',!c);}
function render(){renderShell();const o=state.media?.overview;if(!o?.connected){clearCollections();return;}const p=o.playback?._error?null:o.playback,track=p?.item||null;
  $('#spotifyProfileName').textContent=o.profile?.displayName||state.integrations?.spotify?.metadata?.displayName||'SPOTIFY USER';$('#spotifyPlan').textContent=(o.profile?.product||state.integrations?.spotify?.metadata?.product||'UNKNOWN').toUpperCase();
  $('#spotifyTrack').textContent=track?.name||'Nothing playing';$('#spotifyArtist').textContent=artistOf(track);$('#spotifyPlaybackState').textContent=p?.isPlaying?'PLAYBACK // LIVE':'PLAYBACK // PAUSED';
  const art=artOf(track);$('#spotifyArt').classList.toggle('hidden',!art);$('#spotifyArtFallback').classList.toggle('hidden',!!art);if(art)$('#spotifyArt').src=art;
  const open=$('#spotifyOpenTrack');open.classList.toggle('hidden',!track?.externalUrl);if(track?.externalUrl)open.href=track.externalUrl;
  $('#spotifyPlayPause').textContent=p?.isPlaying?'❚❚':'▶';$('#spotifyShuffle').classList.toggle('active',!!p?.shuffleState);$('#spotifyRepeat').classList.toggle('active',(p?.repeatState||'off')!=='off');$('#spotifyRepeat').title=`Repeat // ${(p?.repeatState||'off').toUpperCase()}`;
  renderDevices(o.devices,p);renderQueue(o.queue);renderRecent(o.recent);renderPlaylists(o.playlists);lastPaintAt=Date.now();paintProgress();$('#spotifyLastRefresh').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
}
function renderDevices(devices,p){const list=Array.isArray(devices)?devices:[];const sel=$('#spotifyDevice'),current=p?.device?.id||list.find(x=>x.isActive)?.id||'';sel.innerHTML=list.length?list.map(d=>`<option value="${escapeHtml(d.id||'')}" ${d.id===current?'selected':''}>${escapeHtml(d.name)} // ${escapeHtml((d.type||'device').toUpperCase())}${d.isRestricted?' // RESTRICTED':''}</option>`).join(''):'<option value="">NO DEVICES</option>';
  const d=list.find(x=>x.id===current)||p?.device||null;$('#spotifyActiveDevice').textContent=d?.name||'NONE';$('#spotifyDeviceMeta').textContent=d?`${(d.type||'DEVICE').toUpperCase()} // ${d.isActive?'ACTIVE':'AVAILABLE'}${d.isRestricted?' // RESTRICTED':''}`:'NO ACTIVE DEVICE';const v=d?.volumePercent;$('#spotifyVolume').disabled=v==null||d?.supportsVolume===false;$('#spotifyVolume').value=v??50;$('#spotifyVolumeValue').textContent=v==null?'—':`${v}%`;}
function renderQueue(q){const list=q&&!q._error?q.items||[]:[];$('#spotifyQueueCount').textContent=`${list.length} ITEMS`;$('#spotifyQueue').innerHTML=list.length?list.map((t,i)=>`<a class="media-list-row" href="${escapeHtml(t.externalUrl||'#')}" ${t.externalUrl?'target="_blank" rel="noopener"':''}><span class="media-index">${String(i+1).padStart(2,'0')}</span><span class="media-thumb">${img(artOf(t),t.name)}</span><span class="media-track-copy"><b>${escapeHtml(t.name)}</b><small>${escapeHtml(artistOf(t))}</small></span><span class="media-duration">${fmtMs(t.durationMs)}</span></a>`).join(''):'<div class="media-empty">QUEUE EMPTY / UNAVAILABLE</div>';}
function renderRecent(items){const list=Array.isArray(items)?items:[];$('#spotifyRecentCount').textContent=`${list.length} ITEMS`;$('#spotifyRecent').innerHTML=list.length?list.map(t=>`<a class="media-list-row" href="${escapeHtml(t.externalUrl||'#')}" ${t.externalUrl?'target="_blank" rel="noopener"':''}><span class="media-thumb">${img(artOf(t),t.name)}</span><span class="media-track-copy"><b>${escapeHtml(t.name)}</b><small>${escapeHtml(artistOf(t))}</small></span><span class="media-played">${t.playedAt?new Date(t.playedAt).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—'}</span></a>`).join(''):'<div class="media-empty">NO RECENT HISTORY RETURNED</div>';}
function renderPlaylists(items){const list=Array.isArray(items)?items:[];$('#spotifyPlaylistCount').textContent=`${list.length} LISTS`;$('#spotifyPlaylists').innerHTML=list.length?list.map(p=>`<article class="playlist-card"><a href="${escapeHtml(p.externalUrl||'#')}" ${p.externalUrl?'target="_blank" rel="noopener"':''}>${img(p.images?.[0]?.url,p.name)}<div><b>${escapeHtml(p.name)}</b><small>${Number(p.tracksTotal)||0} ITEMS</small></div></a><button type="button" class="ghost playlist-play" data-uri="${escapeHtml(p.uri||'')}">▶ PLAY</button></article>`).join(''):'<div class="media-empty">NO PLAYLISTS RETURNED</div>';document.querySelectorAll('.playlist-play').forEach(b=>b.onclick=()=>action('play',{contextUri:b.dataset.uri,deviceId:$('#spotifyDevice').value||undefined}));}
function clearCollections(){['spotifyQueue','spotifyRecent','spotifyPlaylists'].forEach(id=>{const e=$('#'+id);if(e)e.innerHTML='<div class="media-empty">CONNECT SPOTIFY TO LOAD DATA</div>';});}
function renderError(msg){$('#spotifyStatus').textContent='DEGRADED';$('#spotifyStatus').dataset.state='danger';$('#spotifyPlaybackState').textContent='SPOTIFY // ERROR';$('#spotifyTrack').textContent=msg||'Spotify request failed';}
function paintProgress(forceValue=null){const p=state.media?.overview?.playback,item=p?.item;if(!item?.durationMs){$('#spotifyProgress').value=0;$('#spotifyElapsed').textContent='0:00';$('#spotifyDuration').textContent='0:00';return;}let ms=p.progressMs||0;if(forceValue==null&&p.isPlaying)ms+=Math.max(0,Date.now()-lastPaintAt);ms=Math.min(item.durationMs,ms);const ratio=forceValue==null?ms/item.durationMs:Number(forceValue)/1000;$('#spotifyProgress').value=Math.round(ratio*1000);$('#spotifyElapsed').textContent=fmtMs(ratio*item.durationMs);$('#spotifyDuration').textContent=fmtMs(item.durationMs);}
function tickProgress(){if(seekBusy)return;if(document.querySelector('#pageMedia')?.classList.contains('active'))paintProgress();}
async function action(actionName,extra={}){if(!connected())return spotifyConnect();try{await api('/api/v8/spotify/player',{method:'POST',body:{action:actionName,...extra}});if(actionName==='pause'&&state.media?.overview?.playback)state.media.overview.playback.isPlaying=false;if(actionName==='play'&&state.media?.overview?.playback)state.media.overview.playback.isPlaying=true;render();setTimeout(()=>refreshMedia(false),450);}catch(e){toast(e.message,true);}}
async function disconnect(){if(!confirm('Disconnect Spotify from Neon Ops?'))return;try{await api('/api/v8/spotify',{method:'DELETE'});delete state.integrations.spotify;state.media={overview:null,loaded:true};renderShell();render();toast('SPOTIFY DISCONNECTED');}catch(e){toast(e.message,true);}}
