import { api } from './api.js';
import { state } from './state.js';

const KEY='neon_phase9a_allowance_futures_v1';
const MODE_KEY='neon_phase9_allowance_mode_v2';
const PAGE_SIZE=5;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const clamp=(n,a,b)=>Math.min(b,Math.max(a,Number(n)||0));
const uid=()=>crypto.randomUUID?.()||`fut_${Date.now()}_${Math.random().toString(36).slice(2)}`;
let page=0,notify=()=>{},records=loadLocal(),serverAvailable=false,mode=localStorage.getItem(MODE_KEY)==='FUTURES'?'FUTURES':'SPOT';

function loadLocal(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(records));window.dispatchEvent(new CustomEvent('neon:phase9a-contextchange'));}
function sortedRows(){return[...records].sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate))||String(a.title).localeCompare(String(b.title)));}
function currency(){return state.finance?.settings?.currency||'SGD';}
function money(v){try{return new Intl.NumberFormat('en-SG',{style:'currency',currency:currency(),maximumFractionDigits:2}).format(Number(v)||0)}catch{return`${currency()} ${(Number(v)||0).toFixed(2)}`}}
function spot(){const f=state.finance||{},s=f.settings||{},tx=f.transactions||[];const inflow=tx.filter(x=>x.direction==='inflow').reduce((a,x)=>a+Math.abs(Number(x.amount)||0),0),expenses=tx.filter(x=>x.direction==='expense').reduce((a,x)=>a+Math.abs(Number(x.amount)||0),0),base=Number(s.startingBalance)||0;return{base,inflow,expenses,remaining:base+inflow-expenses};}
function probability(r){if(String(r.certainty).toUpperCase()==='COMMITTED')return 1;if(Number.isFinite(Number(r.probability)))return clamp(Number(r.probability)/100,0,1);return String(r.certainty).toUpperCase()==='PLANNED'?.75:.4;}

export function futuresSnapshot(){
  const s=spot(),all=sortedRows(),expected=all.reduce((a,r)=>a+Math.abs(Number(r.amount)||0)*probability(r),0),committed=all.filter(r=>String(r.certainty).toUpperCase()==='COMMITTED').reduce((a,r)=>a+Math.abs(Number(r.amount)||0),0),projected=s.remaining-expected,denom=Math.max(1,s.base+s.inflow),spotIndex=clamp(s.remaining/denom*100,0,100),futuresIndex=clamp(projected/denom*100,0,100);
  const next7=all.filter(r=>{const t=new Date(`${r.dueDate}T23:59:59+08:00`).getTime()-Date.now();return t>=0&&t<=7*86400000;}).reduce((a,r)=>a+Math.abs(Number(r.amount)||0)*probability(r),0);
  return{spotRemaining:s.remaining,expectedFutureOutflow:expected,committedOutflow:committed,projectedRemaining:projected,spotIndex,futuresIndex,next7DaysExpected:next7,count:all.length,rows:all.map(r=>({...r,expectedValue:Math.abs(Number(r.amount)||0)*probability(r)}))};
}
export function futuresSummary(){const x=futuresSnapshot();if(!x.count)return'No future expenses logged. Spot and forecast allowance are aligned.';if(x.projectedRemaining<0)return`Projected allowance turns negative by ${money(Math.abs(x.projectedRemaining))} after expected future expenses. Review near-term commitments.`;if(x.next7DaysExpected>Math.max(1,x.spotRemaining)*.4)return`${money(x.next7DaysExpected)} of expected expenses fall within 7 days. Near-term allowance pressure is elevated.`;if(x.futuresIndex+15<x.spotIndex)return`Spot allowance remains healthy, but expected obligations reduce the forward index by ${Math.round(x.spotIndex-x.futuresIndex)} points.`;return`Expected future outflow is ${money(x.expectedFutureOutflow)}, leaving a projected ${money(x.projectedRemaining)}.`;}

function deckHtml(){return `<div id="allowanceFuturesDeck" class="p9-futures-deck hidden" aria-label="Allowance futures">
  <div class="p9-futures-metrics">
    <div><span>SPOT REMAINING</span><b id="futureSpot">—</b></div><div><span>EXPECTED FUTURES</span><b id="futureExpected">—</b></div><div><span>PROJECTED</span><b id="futureProjected">—</b></div><div><span>SPOT INDEX</span><b id="futureSpotIndex">—</b></div><div><span>FUTURES INDEX</span><b id="futureFuturesIndex">—</b></div>
  </div>
  <div class="p9-overlap-strip"><span>OVERLAP INTELLIGENCE</span><p id="futureSummary">—</p></div>
  <div class="p9-futures-workspace">
    <section class="p9-futures-chart-card"><div class="p9-futures-card-head"><div><small>FORWARD CASHFLOW</small><strong>Projected Balance</strong></div><span id="futureSyncState" class="p9-sync-badge" data-state="local">LOCAL CACHE</span></div><div class="p9-futures-curve"><svg id="futureCurve" viewBox="0 0 1000 220" preserveAspectRatio="none" aria-label="Projected allowance balance curve"></svg></div></section>
    <section class="p9-futures-ledger-card"><div class="p9-futures-card-head"><div><small>FORECAST LEDGER</small><strong>Future Expenses</strong></div><div class="p9-futures-pager"><button id="futurePrev" type="button" aria-label="Previous futures page">←</button><span id="futurePager">0 / 0</span><button id="futureNext" type="button" aria-label="Next futures page">→</button></div></div><div class="p9-future-table-head"><span>OBLIGATION</span><span>DUE</span><span>EXPECTED</span><span>PROB.</span></div><div id="futureRecords"></div></section>
  </div>
</div>`;}
function modeHtml(){return `<div id="p9AllowanceModebar" class="p9-cash-modebar"><div class="p9-cash-segments" role="group" aria-label="Allowance view"><button type="button" data-p9-cash-mode="SPOT">SPOT</button><button type="button" data-p9-cash-mode="FUTURES">FUTURES</button></div><div class="p9-cash-mode-readout"><span><small>SPOT</small><b id="p9ModeSpot">—</b></span><span><small>PROJECTED</small><b id="p9ModeProjected">—</b></span></div><button id="futureAddBtn" type="button" class="primary small p9-future-add">+ FUTURE EXPENSE</button></div>`;}
function dialogHtml(){return `<dialog id="futureDialog" class="modal"><form id="futureForm" method="dialog"><input id="futureId" type="hidden"><div class="modal-head"><div><span class="kicker">ALLOWANCE FORECAST</span><h2 id="futureDialogTitle">Future Expense</h2></div><button type="button" class="x" data-future-close>×</button></div><label>Title<input id="futureTitle" maxlength="180" required></label><div class="two"><label>Amount<input id="futureAmount" type="number" min="0.01" step="0.01" required></label><label>Due date<input id="futureDate" type="date" required></label></div><div class="two"><label>Category<select id="futureCategory"><option>FOOD</option><option>TRANSPORT</option><option>ENTERTAINMENT</option><option>SHOPPING</option><option>SUBSCRIPTIONS</option><option>EDUCATION</option><option>FITNESS</option><option>PERSONAL</option><option>TRAVEL</option><option>OTHER</option></select></label><label>Certainty<select id="futureCertainty"><option>COMMITTED</option><option selected>PLANNED</option><option>POSSIBLE</option></select></label></div><label>Probability <span id="futureProbabilityValue" class="field-value">75%</span><input id="futureProbability" type="range" min="0" max="100" step="5" value="75"></label><label>Notes<textarea id="futureNotes" rows="3" maxlength="1200"></textarea></label><div class="modal-actions"><button type="button" id="futureDeleteBtn" class="danger hidden">DELETE</button><span></span><button type="button" class="ghost" data-future-close>CANCEL</button><button type="submit" class="primary">SAVE FUTURE</button></div></form></dialog>`;}

function inject(){
  const cash=$('.cash-panel');if(!cash)return;
  const head=cash.querySelector(':scope > .panel-head');
  if(!$('#p9AllowanceModebar'))head?.insertAdjacentHTML('afterend',modeHtml());
  if(!$('#allowanceFuturesDeck'))cash.insertAdjacentHTML('beforeend',deckHtml());
  [...cash.children].forEach(el=>{if(el!==head&&el.id!=='p9AllowanceModebar'&&el.id!=='allowanceFuturesDeck')el.dataset.p9CashLayer='spot';});
  if(!$('#futureDialog'))document.body.insertAdjacentHTML('beforeend',dialogHtml());
}
function setMode(next){mode=next==='FUTURES'?'FUTURES':'SPOT';localStorage.setItem(MODE_KEY,mode);const cash=$('.cash-panel');cash?.classList.toggle('p9-futures-mode',mode==='FUTURES');document.querySelectorAll('[data-p9-cash-mode]').forEach(b=>b.classList.toggle('active',b.dataset.p9CashMode===mode));document.querySelectorAll('[data-p9-cash-layer="spot"]').forEach(el=>el.classList.toggle('hidden',mode==='FUTURES'));$('#allowanceFuturesDeck')?.classList.toggle('hidden',mode!=='FUTURES');cash?.querySelectorAll(':scope > .panel-head .actions > button').forEach(b=>b.classList.toggle('p9-mode-hidden',mode==='FUTURES'&&b.id!=='financeSettingsBtn'));render();}
function todaySg(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function openFuture(row=null){const today=todaySg();$('#futureId').value=row?.id||'';$('#futureDialogTitle').textContent=row?'Edit Future Expense':'Future Expense';$('#futureTitle').value=row?.title||'';$('#futureAmount').value=row?.amount??'';$('#futureDate').min=today;$('#futureDate').value=row?.dueDate||today;$('#futureCategory').value=row?.category||'OTHER';$('#futureCertainty').value=row?.certainty||'PLANNED';$('#futureProbability').value=row?.probability??(row?.certainty==='COMMITTED'?100:row?.certainty==='POSSIBLE'?40:75);$('#futureProbabilityValue').textContent=`${$('#futureProbability').value}%`;$('#futureNotes').value=row?.notes||'';$('#futureDeleteBtn').classList.toggle('hidden',!row);$('#futureDialog').showModal();}
function renderCurve(x){const svg=$('#futureCurve');if(!svg)return;const pts=[{date:new Date(),balance:x.spotRemaining},...x.rows.map(r=>({date:new Date(`${r.dueDate}T12:00:00+08:00`),balance:0,expected:r.expectedValue}))].sort((a,b)=>a.date-b.date);let bal=x.spotRemaining;for(let i=1;i<pts.length;i++){bal-=pts[i].expected||0;pts[i].balance=bal;}const ys=pts.map(p=>p.balance),min=Math.min(0,...ys),max=Math.max(1,...ys),span=Math.max(1,max-min),n=Math.max(1,pts.length-1),coords=pts.map((p,i)=>`${(i/n)*1000},${200-((p.balance-min)/span)*170}`).join(' '),zeroY=200-((0-min)/span)*170;svg.innerHTML=`<line x1="0" y1="${zeroY}" x2="1000" y2="${zeroY}" class="futures-zero"/><polyline points="${coords}" class="futures-line"/>${pts.map((p,i)=>`<circle cx="${(i/n)*1000}" cy="${200-((p.balance-min)/span)*170}" r="5" class="futures-dot"><title>${esc(i?pts[i].date.toLocaleDateString('en-SG'):'SPOT')} // ${esc(money(p.balance))}</title></circle>`).join('')}`;}
function render(){const x=futuresSnapshot();if($('#p9ModeSpot'))$('#p9ModeSpot').textContent=money(x.spotRemaining);if($('#p9ModeProjected'))$('#p9ModeProjected').textContent=money(x.projectedRemaining);if(!$('#allowanceFuturesDeck'))return;$('#futureSpot').textContent=money(x.spotRemaining);$('#futureExpected').textContent=money(x.expectedFutureOutflow);$('#futureProjected').textContent=money(x.projectedRemaining);$('#futureProjected').dataset.band=x.projectedRemaining<0?'bad':x.futuresIndex<40?'watch':'good';$('#futureSpotIndex').textContent=String(Math.round(x.spotIndex));$('#futureFuturesIndex').textContent=String(Math.round(x.futuresIndex));$('#futureSummary').textContent=futuresSummary();const sync=$('#futureSyncState');if(sync){sync.textContent=serverAvailable?'D1 SYNC':'LOCAL CACHE';sync.dataset.state=serverAvailable?'live':'local';}renderCurve(x);const total=x.rows.length,pages=Math.max(1,Math.ceil(total/PAGE_SIZE));page=Math.min(Math.max(0,page),pages-1);const slice=x.rows.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE),root=$('#futureRecords');root.replaceChildren();if(!slice.length)root.innerHTML='<div class="future-empty">NO FUTURE EXPENSES // FORECASTS NEVER ALTER THE SPOT LEDGER</div>';for(const r of slice){const row=document.createElement('button');row.type='button';row.className='future-record';row.innerHTML=`<span><b>${esc(r.title)}</b><small>${esc(r.category)} // ${esc(r.certainty)}</small></span><span><b>${esc(r.dueDate)}</b><small>DUE DATE</small></span><span><b>${esc(money(r.expectedValue))}</b><small>OF ${esc(money(r.amount))}</small></span><span><b>${Math.round(probability(r)*100)}%</b><small>PROB.</small></span>`;row.onclick=()=>openFuture(r);root.append(row);}$('#futurePager').textContent=total?`${page+1} / ${pages}`:'0 / 0';$('#futurePrev').disabled=page<=0;$('#futureNext').disabled=page>=pages-1;}

async function hydrateServer(){try{const d=await api('/api/v8/phase9/futures');if(!Array.isArray(d.items))return;serverAvailable=true;const remote=d.items,local=loadLocal();const ids=new Set(remote.map(x=>String(x.id)));for(const r of local){if(ids.has(String(r.id)))continue;try{await api('/api/v8/phase9/futures',{method:'POST',body:r});}catch{}}
    const fresh=await api('/api/v8/phase9/futures');records=Array.isArray(fresh.items)?fresh.items:remote;saveLocal();render();
  }catch(e){if(e.status!==404&&e.status!==503)console.warn('Allowance Futures server unavailable',e);serverAvailable=false;records=loadLocal();render();}}
async function persist(row,isUpdate=false){if(serverAvailable){const out=await api(isUpdate?`/api/v8/phase9/futures/${encodeURIComponent(row.id)}`:'/api/v8/phase9/futures',{method:isUpdate?'PATCH':'POST',body:row});const item=out.item||row,idx=records.findIndex(x=>String(x.id)===String(item.id));if(idx>=0)records[idx]=item;else records.push(item);saveLocal();return item;}const idx=records.findIndex(x=>String(x.id)===String(row.id));if(idx>=0)records[idx]=row;else records.push(row);saveLocal();return row;}
async function removeRecord(id){if(serverAvailable)await api(`/api/v8/phase9/futures/${encodeURIComponent(id)}`,{method:'DELETE'});records=records.filter(x=>String(x.id)!==String(id));saveLocal();}
function bind(){
  document.querySelectorAll('[data-p9-cash-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.p9CashMode));$('#futureAddBtn').onclick=()=>openFuture();$('#futurePrev').onclick=()=>{page=Math.max(0,page-1);render();};$('#futureNext').onclick=()=>{page++;render();};document.querySelectorAll('[data-future-close]').forEach(b=>b.onclick=()=>$('#futureDialog').close());
  $('#futureProbability').oninput=()=>$('#futureProbabilityValue').textContent=`${$('#futureProbability').value}%`;$('#futureCertainty').onchange=()=>{const c=$('#futureCertainty').value;if(c==='COMMITTED')$('#futureProbability').value=100;else if(c==='PLANNED'&&Number($('#futureProbability').value)===100)$('#futureProbability').value=75;else if(c==='POSSIBLE'&&Number($('#futureProbability').value)>=75)$('#futureProbability').value=40;$('#futureProbabilityValue').textContent=`${$('#futureProbability').value}%`;};
  $('#futureForm').onsubmit=async e=>{e.preventDefault();const id=$('#futureId').value||uid(),old=records.find(x=>String(x.id)===String(id)),row={id,title:$('#futureTitle').value.trim(),amount:Number($('#futureAmount').value),dueDate:$('#futureDate').value,category:$('#futureCategory').value,certainty:$('#futureCertainty').value,probability:Number($('#futureProbability').value),notes:$('#futureNotes').value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(!row.title||!Number.isFinite(row.amount)||row.amount<=0||!row.dueDate)return notify('Future expense needs title, amount and date.',true);try{await persist(row,!!old);$('#futureDialog').close();page=0;render();notify(serverAvailable?'FUTURE SAVED // D1 SYNC':'FUTURE SAVED // LOCAL CACHE');}catch(err){notify(err.message,true);}};
  $('#futureDeleteBtn').onclick=async()=>{const id=$('#futureId').value;if(!id||!confirm('Delete this future expense?'))return;try{await removeRecord(id);$('#futureDialog').close();render();notify('FUTURE EXPENSE DELETED');}catch(err){notify(err.message,true);}};
  window.addEventListener('neon:financechange',render);window.addEventListener('neon:phase9a-contextchange',render);
}
export async function initAllowanceFutures(onNotify){notify=onNotify||notify;inject();bind();setMode(mode);await hydrateServer();return{snapshot:futuresSnapshot,refresh:render};}
export function refreshAllowanceFutures(){render();}
