import { api } from './api.js';
import { activatePage,setUnreadState } from './phase9b1-nav.js';

const $=s=>document.querySelector(s);
let notify=()=>{},items=[],filter='ALL',selectedId=null,timer=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function fmt(iso){if(!iso)return'—';const d=new Date(iso),delta=Date.now()-d.getTime();if(delta<60000)return'NOW';if(delta<3600000)return`${Math.max(1,Math.floor(delta/60000))}M AGO`;if(delta<86400000)return`${Math.floor(delta/3600000)}H AGO`;return d.toLocaleString('en-SG',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false});}
function inject(){const page=$('#pageMail');if(!page||$('#p91Mailbox'))return;page.innerHTML=`<section id="p91Mailbox" class="p91-mail-shell"><section class="panel p91-mail-list-panel"><div class="panel-head p91-page-head"><div><span class="kicker">MAILBOX // INTELLIGENCE ROUTER</span><h2>Operational Mailbox</h2></div><div class="actions"><span id="p91MailUnread" class="p91-count-pill">0 UNREAD</span><button id="p91MailClearRead" class="ghost small" type="button">CLEAR READ</button><button id="p91MailRefresh" class="ghost small" type="button">REFRESH</button></div></div><div class="p91-mail-toolbar"><div class="p91-segments" id="p91MailFilters"><button data-filter="ALL" class="active">ALL</button><button data-filter="UNREAD">UNREAD</button><button data-filter="TASK_CHECKIN">CHECK-INS</button><button data-filter="REPORT">REPORTS</button><button data-filter="SIGNAL">ALERTS</button></div><input id="p91MailSearch" type="search" placeholder="Search mailbox…" aria-label="Search mailbox"></div><div id="p91MailList" class="p91-mail-list"></div></section><section class="panel p91-mail-reader-panel"><div class="panel-head compact"><div><span class="kicker">MESSAGE</span><h2 id="p91MailReaderTitle">Select an item</h2></div><span id="p91MailReaderState" class="p91-mini-state">STANDBY</span></div><div id="p91MailReader" class="p91-mail-reader"><div class="p91-empty">SELECT A MESSAGE TO OPEN ITS DETAILS AND ROUTING ACTIONS.</div></div></section></section>`;bind();}
function filtered(){const q=($('#p91MailSearch')?.value||'').trim().toLowerCase();return items.filter(x=>(filter==='ALL'||filter==='UNREAD'&&x.status==='UNREAD'||x.type===filter)&&(!q||`${x.title} ${x.body} ${x.type}`.toLowerCase().includes(q)));}
function render(){const unread=items.filter(x=>x.status==='UNREAD').length;setUnreadState(unread);$('#p91MailUnread').textContent=`${unread} UNREAD`;const root=$('#p91MailList'),rows=filtered();root.replaceChildren();if(!rows.length){root.innerHTML='<div class="p91-empty">NO MAIL IN THIS VIEW</div>';return;}for(const x of rows){const b=document.createElement('button');b.type='button';b.className=`p91-mail-row ${x.status==='UNREAD'?'unread':''} ${x.id===selectedId?'selected':''}`;b.innerHTML=`<i class="p91-mail-priority" data-priority="${esc(x.priority)}"></i><span><b>${esc(x.type.replaceAll('_',' '))}</b><strong>${esc(x.title)}</strong><small>${esc((x.body||'').slice(0,130))}</small></span><time>${esc(fmt(x.createdAt))}</time>`;b.onclick=()=>openMail(x.id);root.append(b);}if(selectedId&&!items.some(x=>x.id===selectedId)){selectedId=null;renderReader(null);}}
function renderReader(x){const root=$('#p91MailReader');if(!x){$('#p91MailReaderTitle').textContent='Select an item';$('#p91MailReaderState').textContent='STANDBY';root.innerHTML='<div class="p91-empty">SELECT A MESSAGE TO OPEN ITS DETAILS AND ROUTING ACTIONS.</div>';return;}$('#p91MailReaderTitle').textContent=x.title;$('#p91MailReaderState').textContent=x.status;root.innerHTML=`<div class="p91-mail-message-meta"><span>${esc(x.type.replaceAll('_',' '))}</span><span>${esc(x.priority)}</span><time>${esc(fmt(x.createdAt))}</time></div><div class="p91-mail-message-body">${esc(x.body||'').replace(/\n/g,'<br>')}</div><div class="p91-mail-actions"><button id="p91MailPrimary" type="button" class="primary">${esc(actionLabel(x.actionRoute))}</button><button id="p91MailToggleRead" type="button" class="ghost">${x.status==='UNREAD'?'MARK READ':'MARK UNREAD'}</button><button id="p91MailDelete" type="button" class="danger">DELETE</button></div>`;$('#p91MailPrimary').disabled=!x.actionRoute;$('#p91MailPrimary').onclick=()=>route(x);$('#p91MailToggleRead').onclick=()=>setRead(x,x.status==='UNREAD');$('#p91MailDelete').onclick=()=>deleteOne(x);}
function actionLabel(route){return({TASK_CHECKIN:'BEGIN CHECK-IN',TASK:'OPEN TASK',SIGNAL:'VIEW SIGNAL',FINANCE:'OPEN FINANCE',NEXUS:'OPEN NEXUS',REMINDER:'OPEN REMINDER'})[route]||'OPEN SOURCE';}
async function openMail(id){selectedId=id;let x=items.find(i=>i.id===id);if(!x)return;if(x.status==='UNREAD'){try{const d=await api(`/api/v8/phase9b1/mail/${encodeURIComponent(id)}`,{method:'PATCH',body:{status:'READ'}});x=d.item||{...x,status:'READ'};items=items.map(i=>i.id===id?x:i);}catch{}}render();renderReader(x);}
async function setRead(x,read){try{const d=await api(`/api/v8/phase9b1/mail/${encodeURIComponent(x.id)}`,{method:'PATCH',body:{status:read?'READ':'UNREAD'}});items=items.map(i=>i.id===x.id?(d.item||{...i,status:read?'READ':'UNREAD'}):i);render();renderReader(items.find(i=>i.id===x.id));}catch(e){notify(e.message,true);}}
async function deleteOne(x){if(!confirm('Delete this mailbox item and clear its mailbox storage?'))return;try{await api(`/api/v8/phase9b1/mail/${encodeURIComponent(x.id)}`,{method:'DELETE'});items=items.filter(i=>i.id!==x.id);selectedId=null;render();renderReader(null);notify('MAIL ITEM DELETED');}catch(e){notify(e.message,true);}}
function route(x){const p=x.actionPayload||{};if(x.actionRoute==='TASK_CHECKIN'){window.dispatchEvent(new CustomEvent('neon:phase9b1-task-checkin',{detail:{taskId:p.taskId||x.sourceRecordId,mailId:x.id}}));return;}if(x.actionRoute==='SIGNAL'){activatePage('pageSignals');setTimeout(()=>window.dispatchEvent(new CustomEvent('neon:phase9b1-open-signal',{detail:{signalId:p.signalId||x.sourceRecordId}})),50);return;}if(x.actionRoute==='FINANCE'){activatePage('pageFinance');return;}if(x.actionRoute==='NEXUS'){activatePage('pageNexus');return;}if(x.actionRoute==='TASK'){activatePage('pageOps');return;}if(x.actionRoute==='REMINDER'){activatePage('pageOps');return;}if(x.actionRoute)activatePage(x.actionRoute);}
async function refresh({materialize=true,silent=true}={}){try{if(materialize)await api('/api/v8/phase9b1/mail/materialize',{method:'POST'}).catch(()=>{});const d=await api('/api/v8/phase9b1/mail?limit=160');items=Array.isArray(d.items)?d.items:[];render();if(selectedId)renderReader(items.find(x=>x.id===selectedId)||null);}catch(e){if(!silent)notify(e.message,true);}}
function bind(){$('#p91MailRefresh').onclick=()=>refresh({materialize:true,silent:false});$('#p91MailClearRead').onclick=async()=>{if(!confirm('Delete all read mailbox items?'))return;try{await api('/api/v8/phase9b1/mail/read',{method:'DELETE'});await refresh({materialize:false,silent:false});}catch(e){notify(e.message,true);}};$('#p91MailSearch').oninput=render;$('#p91MailFilters').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;[...$('#p91MailFilters').children].forEach(x=>x.classList.toggle('active',x===b));render();};window.addEventListener('neon:phase9b1-mail-refresh',()=>refresh({materialize:true,silent:true}));window.addEventListener('neon:phase9b1-page',e=>{if(e.detail?.page==='pageMail')refresh({materialize:true,silent:true});});}
export async function initPhase9CMailbox(onNotify){notify=onNotify||notify;inject();await refresh({materialize:true,silent:true});timer=setInterval(()=>refresh({materialize:true,silent:true}),60*1000);return{refresh,getItems:()=>items};}
