import { api } from './api.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let observer=null;
function injectClusters(){const nav=$('#p91SignalViews');if(!nav||$('#p9d2ClusterTab'))return;const b=document.createElement('button');b.id='p9d2ClusterTab';b.type='button';b.textContent='CLUSTERS';b.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();showClusters();};nav.insertBefore(b,nav.querySelector('[data-view="SAVED"]'));const host=$('#p91Signals');if(host&&!$('#p9d2ClusterWorkspace')){const s=document.createElement('section');s.id='p9d2ClusterWorkspace';s.className='panel p9d2-cluster-workspace hidden';host.append(s);}nav.addEventListener('click',e=>{if(e.target!==b&&e.target.closest('[data-view]'))$('#p9d2ClusterWorkspace')?.classList.add('hidden');},true);}
async function showClusters(){const nav=$('#p91SignalViews');nav?.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x.id==='p9d2ClusterTab'));for(const id of ['#p91SignalsWorkspace','#p91SourcesWorkspace','#p91FiltersWorkspace'])$(id)?.classList.add('hidden');const root=$('#p9d2ClusterWorkspace');root.classList.remove('hidden');root.innerHTML='<div class="p9d2-cluster-loading">CLUSTERING RECENT INTELLIGENCE…</div>';try{const d=await api('/api/v8/phase9d2/signal-clusters?limit=180');root.innerHTML=`<div class="panel-head"><div><span class="kicker">INTELLIGENCE // DEDUPLICATION</span><h2>Corroborated Event Clusters</h2></div><div class="p9d2-cluster-stats"><span>${d.rawCount} RAW</span><span>${d.clusterCount} CLUSTERS</span><span>${d.dedupedCount} DUPLICATES COLLAPSED</span></div></div><div class="p9d2-cluster-list">${(d.items||[]).map(clusterHtml).join('')||'<div class="p9d2-empty">NO SIGNALS TO CLUSTER</div>'}</div>`;}catch(e){root.innerHTML=`<div class="p9d2-empty">CLUSTER LOAD FAILED // ${esc(e.message)}</div>`;}}
function clusterHtml(c){return `<article class="p9d2-cluster"><header><span class="p9d2-cluster-count">${c.signalCount}</span><div><b>${esc(c.title)}</b><small>${esc(c.category||'GENERAL')} // ${c.corroboration} SOURCE${c.corroboration===1?'':'S'} // ${new Date(c.lastAt||Date.now()).toLocaleString('en-SG',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false})}</small></div></header><p>${esc((c.body||'').slice(0,420))}</p><details><summary>CORROBORATING SOURCES</summary>${(c.members||[]).map(m=>`<div class="p9d2-cluster-source"><span>${esc(m.sourceName||m.provider)}</span><b>${esc(m.title)}</b>${m.url?`<a href="${esc(m.url)}" target="_blank" rel="noopener">OPEN ↗</a>`:''}</div>`).join('')}</details></article>`;}
function injectTelegramQuick(){const root=$('#p91SourcesWorkspace');if(!root||$('#p9d2AddTelegram'))return;const head=root.querySelector('.panel-head .actions');if(!head)return;const b=document.createElement('button');b.id='p9d2AddTelegram';b.type='button';b.className='ghost';b.textContent='+ TELEGRAM CHANNEL';b.onclick=()=>{const add=$('#p91AddSource');add?.click();setTimeout(()=>{if($('#p91SourceAdapter')){$('#p91SourceAdapter').value='TELEGRAM';$('#p91SourceAdapter').dispatchEvent(new Event('change'));$('#p91SourceName')?.focus();}},0)};head.append(b);const h=document.createElement('span');h.id='p9d2SourceHealth';h.className='p9d2-source-health';h.textContent='HEALTH // CHECKING';head.prepend(h);sourceHealth();}
async function sourceHealth(){const e=$('#p9d2SourceHealth');if(!e)return;try{const d=await api('/api/v8/phase9d/sources/status'),s=d.sources||[],fail=s.filter(x=>x.lastError).length,ok=s.length-fail,pct=s.length?Math.round(ok/s.length*100):100;e.textContent=`HEALTH // ${pct}% // ${ok} OK${fail?` / ${fail} ERR`:''}`;e.dataset.state=pct>=90?'good':pct>=60?'warn':'bad';}catch(err){e.textContent='HEALTH // UNAVAILABLE';e.dataset.state='bad';}}
function scan(){injectClusters();injectTelegramQuick();}
export function initPhase9D2Intel(){scan();observer=new MutationObserver(scan);observer.observe(document.body,{subtree:true,childList:true});window.addEventListener('neon:phase9b1-signals-refresh',()=>{if(!$('#p9d2ClusterWorkspace')?.classList.contains('hidden'))showClusters();sourceHealth();});return{destroy(){observer?.disconnect()}};}
