import { state } from './state.js';
import { setAvatarTransientState } from './avatar.js';
import { futuresSnapshot,futuresSummary } from './phase9a-futures.js';
import { activeOccurrences,occurrences } from './phase9a-calendar.js';
import { listEventAvatars,objectUrl } from './phase9a-store.js';

const KEY='neon_phase9a_nexus_context_v1';
const DEFAULTS={bubbleEnabled:true,bubbleMaxChars:180,bubbleOpacity:88,bubbleScale:100,avatarCycleSeconds:6};
const $=s=>document.querySelector(s);
let notify=()=>{},settings=load(),timer=null,cycleTimer=null,cycleIndex=0,currentUrl=null;
const sgKey=v=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v));
const clamp=(n,a,b)=>Math.min(b,Math.max(a,Number(n)||0));
function load(){try{return{...DEFAULTS,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return{...DEFAULTS}}}
function save(){localStorage.setItem(KEY,JSON.stringify(settings));applySettings();window.dispatchEvent(new CustomEvent('neon:phase9a-contextchange'));}
function priorityReminder(r){const ms=new Date(r.scheduledAt).getTime()-Date.now();if(!Number.isFinite(ms))return 0;if(ms<0)return 4;if(ms<=6*3600000)return 3;if(ms<=24*3600000)return 2;if(ms<=72*3600000)return 1;return 0;}
function highKeyEvent(ev){const cat=String(ev.category||'').toUpperCase(),title=String(ev.title||'').toLowerCase();const category=['OPERATIONAL','DUTY','TRAVEL','FINANCE'].includes(cat);const keyword=/birthday|exam|test|meeting|appointment|flight|operation|duty|deadline|launch|interview|medical|parade|ceremony|brief|review/.test(title);return category||keyword;}
function portfolioPressure(){const f=state.finance||{},pos=f.positions||[];let entry=0,current=0;for(const p of pos){const q=Math.abs(Number(p.quantity??p.qty)||0),e=Number(p.entryPrice??p.entry)||0,c=Number(p.currentPrice??p.current??e)||e;entry+=q*e;current+=q*c;}const pnlPct=entry?((current-entry)/entry)*100:0;return{pnlPct,negative:pnlPct<=-5,critical:pnlPct<=-10};}
export function contextSnapshot(){
  const now=Date.now(),tasks=state.tasks||[],active=tasks.filter(t=>!['completed','cancelled'].includes(String(t.status||'').toLowerCase())),overdue=active.filter(t=>t.dueAt&&new Date(t.dueAt).getTime()<now),highOverdue=overdue.filter(t=>['high','critical'].includes(String(t.priority||'').toLowerCase())),today=sgKey(new Date()),completedToday=tasks.filter(t=>String(t.status).toLowerCase()==='completed'&&t.completedAt&&sgKey(t.completedAt)===today);
  const next24=occurrences(new Date(now),new Date(now+24*3600000)).filter(highKeyEvent),next6=next24.filter(e=>e.occurrenceStart.getTime()-now<=6*3600000);
  const rem=(state.reminders||[]).filter(r=>['scheduled','snoozed'].includes(r.status)),criticalRem=rem.filter(r=>priorityReminder(r)>=3),highRem=rem.filter(r=>priorityReminder(r)>=2),future=futuresSnapshot(),portfolio=portfolioPressure();
  let mood='RELAXED',reason='LOW CROSS-DOMAIN PRESSURE';
  if(highOverdue.length>=2||future.projectedRemaining<0||criticalRem.length>=2||portfolio.critical){mood='PANIC';reason=highOverdue.length>=2?'HIGH-PRIORITY OVERDUE TASKS':future.projectedRemaining<0?'ALLOWANCE FUTURES NEGATIVE':criticalRem.length>=2?'MULTIPLE CRITICAL REMINDERS':'PORTFOLIO DRAWDOWN';}
  else if(overdue.length||next6.length||criticalRem.length||portfolio.negative||(future.next7DaysExpected>Math.max(1,future.spotRemaining)*.4)){mood='ANXIOUS';reason=overdue.length?'OVERDUE WORKLOAD':next6.length?'HIGH-KEY EVENT APPROACHING':criticalRem.length?'CRITICAL REMINDER':'NEAR-TERM FINANCIAL PRESSURE';}
  else if(completedToday.length>=3&&future.projectedRemaining>=0){mood='SUCCESS';reason='STRONG DAILY COMPLETION';}
  else if(active.length||next24.length||highRem.length){mood='FOCUSED';reason=next24.length?'UPCOMING HIGH-KEY EVENT':highRem.length?'PRIORITY REMINDER':'ACTIVE WORKLOAD';}
  return{mood,reason,tasks:{active:active.length,overdue:overdue.length,highOverdue:highOverdue.length,completedToday:completedToday.length},events:{highKey24h:next24.length,highKey6h:next6.length},reminders:{high:highRem.length,critical:criticalRem.length},finance:{...future,portfolioPnlPct:portfolio.pnlPct},generatedAt:new Date().toISOString()};
}
function deterministicSummary(x=contextSnapshot()){const bits=[];if(x.events.highKey6h)bits.push(`${x.events.highKey6h} high-key event${x.events.highKey6h>1?'s':''} within 6h`);if(x.reminders.critical)bits.push(`${x.reminders.critical} critical reminder${x.reminders.critical>1?'s':''}`);if(x.tasks.overdue)bits.push(`${x.tasks.overdue} overdue objective${x.tasks.overdue>1?'s':''}`);if(x.finance.projectedRemaining<0)bits.push('allowance forecast is negative');else if(x.finance.expectedFutureOutflow)bits.push(futuresSummary().replace(/\.$/,''));return bits.length?`${x.reason}. ${bits.join('; ')}.`:`${x.reason}. ${futuresSummary()}`;}
function latestAiSummary(){const rows=[...(state.ai?.reports||[])].sort((a,b)=>String(b.generatedAt).localeCompare(String(a.generatedAt)));return String(rows[0]?.summary||'').trim();}
function bubbleText(){return latestAiSummary()||deterministicSummary();}
function truncate(s,n){s=String(s||'');return s.length<=n?s:`${s.slice(0,Math.max(1,n-1)).trimEnd()}…`;}
function injectBubble(){
  const card=$('.nexus-card'),core=card?.querySelector('.nexus-core'),copy=core?.querySelector(':scope > div:last-child');
  if(copy&&!$('#phase9aSpeechBubble'))copy.insertAdjacentHTML('beforeend',`<div id="phase9aSpeechBubble" class="phase9a-speech-bubble" role="status" aria-live="polite"><span>NEXUS // CONTEXT</span><p id="phase9aSpeechText">—</p></div>`);
  const stage=$('#nexusStage');if(stage&&!$('#phase9aAvatarMedia'))stage.insertAdjacentHTML('beforeend',`<div id="phase9aAvatarMedia" class="phase9a-avatar-media hidden" aria-hidden="true"></div><div id="phase9aAvatarPager" class="phase9a-avatar-pager hidden"><button type="button" data-avatar-dir="-1" aria-label="Previous NEXUS avatar">‹</button><span id="phase9aAvatarPage">BASE</span><button type="button" data-avatar-dir="1" aria-label="Next NEXUS avatar">›</button></div>`);
}
function injectCustomize(){
  const host=$('.avatar-system-body');if(!host||$('#phase9aNexusSettings'))return;
  host.insertAdjacentHTML('beforeend',`<details class="p9-context-settings" id="phase9aNexusSettings"><summary><div><span>NEXUS // CONTEXT UI</span><b>Speech brief + event avatar</b></div></summary><form id="phase9aNexusForm" class="phase9a-settings-grid"><label class="toggle-card"><input id="p9BubbleEnabled" type="checkbox"><span>SPEECH BRIEF</span><small>Show a compact contextual summary inside the NEXUS card.</small></label><label>Summary length <span id="p9BubbleCharsV"></span><input id="p9BubbleChars" type="range" min="70" max="300" step="10"></label><label>Text scale <span id="p9BubbleScaleV"></span><input id="p9BubbleScale" type="range" min="80" max="125" step="5"></label><label>Brief opacity <span id="p9BubbleOpacityV"></span><input id="p9BubbleOpacity" type="range" min="45" max="100" step="5"></label><label>Avatar cycle <span id="p9AvatarCycleV"></span><input id="p9AvatarCycle" type="range" min="3" max="20" step="1"></label><div class="modal-actions"><span></span><span></span><span></span><button class="primary" type="submit">SAVE CONTEXT UI</button></div></form></details>`);
}
function fillSettings(){if(!$('#phase9aNexusForm'))return;$('#p9BubbleEnabled').checked=settings.bubbleEnabled;$('#p9BubbleOpacity').value=settings.bubbleOpacity;$('#p9BubbleScale').value=settings.bubbleScale;$('#p9BubbleChars').value=settings.bubbleMaxChars;$('#p9AvatarCycle').value=settings.avatarCycleSeconds;updateLabels();}
function updateLabels(){if(!$('#phase9aNexusForm'))return;$('#p9BubbleOpacityV').textContent=`${$('#p9BubbleOpacity').value}%`;$('#p9BubbleScaleV').textContent=`${$('#p9BubbleScale').value}%`;$('#p9BubbleCharsV').textContent=$('#p9BubbleChars').value;$('#p9AvatarCycleV').textContent=`${$('#p9AvatarCycle').value}s`;}
function applySettings(){const b=$('#phase9aSpeechBubble');if(b){b.classList.toggle('hidden',!settings.bubbleEnabled);b.style.setProperty('--p9-bubble-opacity',String(settings.bubbleOpacity/100));b.style.setProperty('--p9-bubble-scale',String(settings.bubbleScale/100));}restartCycle();}
function updateContext(){const x=contextSnapshot(),bubble=$('#phase9aSpeechText');if(bubble)bubble.textContent=truncate(bubbleText(),settings.bubbleMaxChars);const current=$('#nexusMood')?.textContent?.trim().toUpperCase();if(navigator.onLine&&!['OFFLINE','ANALYZING'].includes(current)){const rank={RELAXED:0,FOCUSED:1,SUCCESS:1,ANXIOUS:2,PANIC:3};if((rank[x.mood]||0)>(rank[current]||0))setAvatarTransientState(x.mood,18000,`CONTEXT // ${x.reason}`);}window.dispatchEvent(new CustomEvent('neon:phase9a-snapshot',{detail:x}));updateEventAvatar().catch(()=>{});}
async function activeAvatarRecords(){const active=activeOccurrences(new Date()),assets=await listEventAvatars();const by=new Map(assets.map(a=>[String(a.eventId),a]));return active.map(ev=>({ev,asset:by.get(String(ev.id))})).filter(x=>x.asset).sort((a,b)=>(Number(b.asset.priority)||0)-(Number(a.asset.priority)||0));}
async function updateEventAvatar(){const list=await activeAvatarRecords(),pager=$('#phase9aAvatarPager'),media=$('#phase9aAvatarMedia');if(!pager||!media)return;const total=1+list.length;if(cycleIndex>=total)cycleIndex=0;pager.classList.toggle('hidden',total<=1);$('#phase9aAvatarPage').textContent=cycleIndex===0?'BASE':`${cycleIndex}/${total-1}`;if(currentUrl){URL.revokeObjectURL(currentUrl);currentUrl=null;}media.replaceChildren();if(cycleIndex===0||!list.length){media.classList.add('hidden');return;}const item=list[cycleIndex-1];currentUrl=objectUrl(item.asset);const el=item.asset.type.startsWith('video/')?document.createElement('video'):document.createElement('img');el.src=currentUrl;el.className='phase9a-avatar-override';if(el.tagName==='VIDEO'){el.muted=true;el.autoplay=true;el.loop=true;el.playsInline=true;}else el.alt=`Event avatar: ${item.ev.title}`;media.append(el);media.classList.remove('hidden');media.setAttribute('aria-label',`Event avatar override for ${item.ev.title}`);}
function restartCycle(){clearInterval(cycleTimer);cycleTimer=setInterval(async()=>{const n=1+(await activeAvatarRecords()).length;if(n<=1){cycleIndex=0;return updateEventAvatar();}cycleIndex=(cycleIndex+1)%n;updateEventAvatar();},Math.max(3,Number(settings.avatarCycleSeconds)||6)*1000);}
function bind(){
  $('#phase9aAvatarPager')?.querySelectorAll('button').forEach(b=>b.onclick=async e=>{e.stopPropagation();const n=1+(await activeAvatarRecords()).length;cycleIndex=(cycleIndex+Number(b.dataset.avatarDir)+n)%n;updateEventAvatar();});
  const form=$('#phase9aNexusForm');if(form){for(const id of ['p9BubbleOpacity','p9BubbleScale','p9BubbleChars','p9AvatarCycle'])$('#'+id).oninput=updateLabels;form.onsubmit=e=>{e.preventDefault();settings={...settings,bubbleEnabled:$('#p9BubbleEnabled').checked,bubbleOpacity:Number($('#p9BubbleOpacity').value),bubbleScale:Number($('#p9BubbleScale').value),bubbleMaxChars:Number($('#p9BubbleChars').value),avatarCycleSeconds:Number($('#p9AvatarCycle').value)};save();notify('NEXUS CONTEXT UI SAVED');};}
  window.addEventListener('neon:phase9a-contextchange',updateContext);window.addEventListener('neon:themechange',applySettings);
}
export function initPhase9Nexus(onNotify){notify=onNotify||notify;injectBubble();injectCustomize();fillSettings();applySettings();bind();updateContext();clearInterval(timer);timer=setInterval(updateContext,15000);return{snapshot:contextSnapshot,update:updateContext};}
