import { api } from './api.js';
import { state } from './state.js';
const $=s=>document.querySelector(s);let rows=[],mode='SPOT';
const money=v=>{const c=state.finance?.settings?.currency||'SGD';try{return new Intl.NumberFormat('en-SG',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v)||0)}catch{return`${c} ${(Number(v)||0).toFixed(2)}`}};
const prob=r=>String(r.certainty).toUpperCase()==='COMMITTED'?1:Math.max(0,Math.min(1,(Number(r.probability)||0)/100));
function spot(){const f=state.finance||{},s=f.settings||{},tx=f.transactions||[],ins=tx.filter(x=>x.direction==='inflow').reduce((a,x)=>a+Math.abs(+x.amount||0),0),outs=tx.filter(x=>x.direction==='expense').reduce((a,x)=>a+Math.abs(+x.amount||0),0);return(+s.startingBalance||0)+ins-outs;}
function snapshot(){let incoming=0,outgoing=0;for(const r of rows){const v=Math.abs(+r.amount||0)*prob(r);if(r.direction==='inflow')incoming+=v;else outgoing+=v;}return{incoming,outgoing,net:incoming-outgoing,projected:spot()+incoming-outgoing};}
function inject(){const cash=$('.cash-panel');if(!cash||$('#p9d2FuturesDeck'))return;const d=document.createElement('section');d.id='p9d2FuturesDeck';d.className='p9d2-futures hidden';d.innerHTML=`<div class="p9d2-future-head"><div><span class="kicker">FINANCE // FORWARD CASHFLOW</span><h3>Earnings + Expenses</h3></div><button id="p9d2FutureAdd" class="primary small">+ FUTURE CASHFLOW</button></div><div class="p9d2-future-metrics"><article><span>EXPECTED IN</span><b id="p9d2FutureIn">—</b></article><article><span>EXPECTED OUT</span><b id="p9d2FutureOut">—</b></article><article><span>NET FUTURE</span><b id="p9d2FutureNet">—</b></article><article><span>PROJECTED CASH</span><b id="p9d2FutureProjected">—</b></article></div><div id="p9d2FutureRows" class="p9d2-future-rows"></div>`;cash.append(d);const dlg=document.createElement('dialog');dlg.id='p9d2FutureDialog';dlg.className='modal';dlg.innerHTML=`<form id="p9d2FutureForm"><input id="p9d2FutureId" type="hidden"><div class="modal-head"><div><span class="kicker">FORWARD CASHFLOW</span><h2 id="p9d2FutureTitle">Future Cashflow</h2></div><button type="button" class="x" data-d2close>×</button></div><div class="two"><label>Direction<select id="p9d2FutureDirection"><option value="inflow">EARNING / INFLOW</option><option value="expense">EXPENSE / OUTFLOW</option></select></label><label>Amount<input id="p9d2FutureAmount" type="number" min="0.01" step="0.01" required></label></div><label>Title<input id="p9d2FutureName" maxlength="180" required></label><div class="two"><label>Due date<input id="p9d2FutureDate" type="date" required></label><label>Category<input id="p9d2FutureCategory" maxlength="60" value="OTHER"></label></div><div class="two"><label>Certainty<select id="p9d2FutureCertainty"><option>COMMITTED</option><option selected>PLANNED</option><option>POSSIBLE</option></select></label><label>Probability<input id="p9d2FutureProbability" type="range" min="0" max="100" value="75"><span id="p9d2FutureProbLabel">75%</span></label></div><label>Notes<textarea id="p9d2FutureNotes" rows="3"></textarea></label><div class="modal-actions"><button id="p9d2FutureDelete" type="button" class="danger hidden">DELETE</button><span></span><button type="button" class="ghost" data-d2close>CANCEL</button><button class="primary">SAVE</button></div></form>`;document.body.append(dlg);bind();load();}
function open(r=null){$('#p9d2FutureId').value=r?.id||'';$('#p9d2FutureDirection').value=r?.direction||'expense';$('#p9d2FutureAmount').value=r?.amount||'';$('#p9d2FutureName').value=r?.title||'';$('#p9d2FutureDate').value=r?.dueDate||new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());$('#p9d2FutureCategory').value=r?.category||'OTHER';$('#p9d2FutureCertainty').value=r?.certainty||'PLANNED';$('#p9d2FutureProbability').value=r?.probability??75;$('#p9d2FutureProbLabel').textContent=`${$('#p9d2FutureProbability').value}%`;$('#p9d2FutureNotes').value=r?.notes||'';$('#p9d2FutureDelete').classList.toggle('hidden',!r);$('#p9d2FutureDialog').showModal();}
async function load(){try{const d=await api('/api/v8/phase9/futures');rows=d.items||[];render();}catch(e){console.warn('9D2 futures',e)}}
function render(){const d=$('#p9d2FuturesDeck');if(!d)return;const x=snapshot();$('#p9d2FutureIn').textContent=`+${money(x.incoming)}`;$('#p9d2FutureOut').textContent=`−${money(x.outgoing)}`;$('#p9d2FutureNet').textContent=`${x.net>=0?'+':'−'}${money(Math.abs(x.net))}`;$('#p9d2FutureNet').dataset.sign=x.net>0?'positive':x.net<0?'negative':'neutral';$('#p9d2FutureProjected').textContent=money(x.projected);$('#p9d2FutureProjected').dataset.sign=x.projected>0?'positive':x.projected<0?'negative':'neutral';const root=$('#p9d2FutureRows');root.replaceChildren();if(!rows.length){root.innerHTML='<div class="p9d2-empty">NO FUTURE CASHFLOW // ADD EXPECTED EARNINGS OR EXPENSES</div>';return;}for(const r of [...rows].sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate)))){const b=document.createElement('button');b.type='button';b.className='p9d2-future-row';b.dataset.direction=r.direction||'expense';b.innerHTML=`<span><b>${r.direction==='inflow'?'IN':'OUT'}</b></span><span><strong>${r.title}</strong><small>${r.category||'OTHER'} // ${r.certainty}</small></span><span>${r.dueDate}</span><span>${r.direction==='inflow'?'+':'−'}${money(Math.abs(+r.amount||0)*prob(r))}</span>`;b.onclick=()=>open(r);root.append(b);}}
function enforce(){mode=document.querySelector('[data-p9-cash-mode="FUTURES"]')?.classList.contains('active')?'FUTURES':'SPOT';const old=$('#allowanceFuturesDeck'),ours=$('#p9d2FuturesDeck');if(mode==='FUTURES'){old?.classList.add('hidden');ours?.classList.remove('hidden');$('#futureAddBtn')?.classList.add('hidden');load();}else ours?.classList.add('hidden');}
function bind(){document.addEventListener('click',e=>{if(e.target.closest('[data-p9-cash-mode]'))setTimeout(enforce,0)});$('#p9d2FutureAdd').onclick=()=>open();document.querySelectorAll('[data-d2close]').forEach(b=>b.onclick=()=>$('#p9d2FutureDialog').close());$('#p9d2FutureProbability').oninput=e=>$('#p9d2FutureProbLabel').textContent=`${e.target.value}%`;$('#p9d2FutureForm').onsubmit=async e=>{e.preventDefault();const id=$('#p9d2FutureId').value,body={direction:$('#p9d2FutureDirection').value,amount:Number($('#p9d2FutureAmount').value),title:$('#p9d2FutureName').value.trim(),dueDate:$('#p9d2FutureDate').value,category:$('#p9d2FutureCategory').value.trim().toUpperCase()||'OTHER',certainty:$('#p9d2FutureCertainty').value,probability:Number($('#p9d2FutureProbability').value),notes:$('#p9d2FutureNotes').value.trim()};await api(id?`/api/v8/phase9/futures/${encodeURIComponent(id)}`:'/api/v8/phase9/futures',{method:id?'PATCH':'POST',body});$('#p9d2FutureDialog').close();await load();window.dispatchEvent(new CustomEvent('neon:phase9a-contextchange'));};$('#p9d2FutureDelete').onclick=async()=>{const id=$('#p9d2FutureId').value;if(!id||!confirm('Delete this future cashflow item?'))return;await api(`/api/v8/phase9/futures/${encodeURIComponent(id)}`,{method:'DELETE'});$('#p9d2FutureDialog').close();load();};setTimeout(enforce,500);}
export function initPhase9D2Finance(){inject();return{refresh:load};}
