import { state } from './state.js';

const KEY='neon_phase9a_allowance_futures_v1';
const PAGE_SIZE=5;
let page=0,notify=()=>{};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const clamp=(n,a,b)=>Math.min(b,Math.max(a,Number(n)||0));
const uid=()=>crypto.randomUUID?.()||`fut_${Date.now()}_${Math.random().toString(36).slice(2)}`;

function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function save(rows){localStorage.setItem(KEY,JSON.stringify(rows));window.dispatchEvent(new CustomEvent('neon:phase9a-contextchange'));}
function rows(){return load().sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate)));}
function currency(){return state.finance?.settings?.currency||'SGD';}
function money(v){try{return new Intl.NumberFormat('en-SG',{style:'currency',currency:currency(),maximumFractionDigits:2}).format(Number(v)||0)}catch{return `${currency()} ${(Number(v)||0).toFixed(2)}`}}
function spot(){const f=state.finance||{},s=f.settings||{},tx=f.transactions||[];const inflow=tx.filter(x=>x.direction==='inflow').reduce((a,x)=>a+Math.abs(Number(x.amount)||0),0),expenses=tx.filter(x=>x.direction==='expense').reduce((a,x)=>a+Math.abs(Number(x.amount)||0),0),base=Number(s.startingBalance)||0;return{base,inflow,expenses,remaining:base+inflow-expenses};}
function probability(r){if(r.certainty==='COMMITTED')return 1;if(Number.isFinite(Number(r.probability)))return clamp(Number(r.probability)/100,0,1);return r.certainty==='PLANNED'?.75:.4;}
export function futuresSnapshot(){
  const s=spot(),all=rows(),expected=all.reduce((a,r)=>a+Math.abs(Number(r.amount)||0)*probability(r),0),committed=all.filter(r=>r.certainty==='COMMITTED').reduce((a,r)=>a+Math.abs(Number(r.amount)||0),0),projected=s.remaining-expected,denom=Math.max(1,s.base+s.inflow),spotIndex=clamp(s.remaining/denom*100,0,100),futuresIndex=clamp(projected/denom*100,0,100);
  const next7=all.filter(r=>{const t=new Date(`${r.dueDate}T23:59:59+08:00`).getTime()-Date.now();return t>=0&&t<=7*86400000;}).reduce((a,r)=>a+Math.abs(Number(r.amount)||0)*probability(r),0);
  return{spotRemaining:s.remaining,expectedFutureOutflow:expected,committedOutflow:committed,projectedRemaining:projected,spotIndex,futuresIndex,next7DaysExpected:next7,count:all.length,rows:all.map(r=>({...r,expectedValue:Math.abs(Number(r.amount)||0)*probability(r)}))};
}
export function futuresSummary(){const x=futuresSnapshot();if(!x.count)return'No future expenses logged. Spot allowance and projected allowance are aligned.';if(x.projectedRemaining<0)return`Projected allowance turns negative by ${money(Math.abs(x.projectedRemaining))} after expected future expenses. Immediate review recommended.`;if(x.next7DaysExpected>Math.max(1,x.spotRemaining)*.4)return`${money(x.next7DaysExpected)} of expected expenses fall within 7 days. Near-term allowance pressure is elevated.`;if(x.futuresIndex+15<x.spotIndex)return`Spot allowance is healthy, but future obligations reduce the forecast index by ${Math.round(x.spotIndex-x.futuresIndex)} points.`;return`Allowance outlook is stable. Expected future outflow is ${money(x.expectedFutureOutflow)} with projected remaining ${money(x.projectedRemaining)}.`;}

function panelHtml(){return `<section class="panel allowance-futures-panel" id="allowanceFuturesPanel">
  <div class="panel-head finance-head"><div><span class="kicker">FINANCE // 09A</span><h2>Allowance Futures</h2></div><div class="actions"><button id="futureAddBtn" class="primary">+ FUTURE EXPENSE</button></div></div>
  <div class="finance-metrics futures-metrics"><div><span>SPOT REMAINING</span><b id="futureSpot">—</b></div><div><span>EXPECTED FUTURES</span><b id="futureExpected">—</b></div><div><span>PROJECTED REMAINING</span><b id="futureProjected">—</b></div><div><span>SPOT INDEX</span><b id="futureSpotIndex">—</b></div><div><span>FUTURES INDEX</span><b id="futureFuturesIndex">—</b></div></div>
  <div class="futures-intel"><span class="kicker">OVERLAP INTELLIGENCE</span><p id="futureSummary">—</p></div>
  <div class="futures-curve-shell"><svg id="futureCurve" viewBox="0 0 1000 220" preserveAspectRatio="none" aria-label="Projected allowance balance curve"></svg></div>
  <div class="finance-ledger"><div class="finance-section-head"><div><span class="kicker">FORECAST LEDGER</span><h3>Future Expenses</h3></div><div class="pager"><button id="futurePrev">←</button><span id="futurePager">0 / 0</span><button id="futureNext">→</button></div></div><div id="futureRecords"></div></div>
</section>`}
function dialogHtml(){return `<dialog id="futureDialog" class="modal"><form id="futureForm" method="dialog"><input id="futureId" type="hidden"><div class="modal-head"><div><span class="kicker">ALLOWANCE FUTURE</span><h2 id="futureDialogTitle">Future Expense</h2></div><button type="button" class="x" data-future-close>×</button></div><label>Title<input id="futureTitle" maxlength="180" required></label><div class="two"><label>Amount<input id="futureAmount" type="number" min="0" step="0.01" required></label><label>Due date<input id="futureDate" type="date" required></label></div><div class="two"><label>Category<select id="futureCategory"><option>FOOD</option><option>TRANSPORT</option><option>ENTERTAINMENT</option><option>SHOPPING</option><option>SUBSCRIPTIONS</option><option>EDUCATION</option><option>FITNESS</option><option>PERSONAL</option><option>TRAVEL</option><option>OTHER</option></select></label><label>Certainty<select id="futureCertainty"><option>COMMITTED</option><option selected>PLANNED</option><option>POSSIBLE</option></select></label></div><label>Probability <span id="futureProbabilityValue">75%</span><input id="futureProbability" type="range" min="0" max="100" step="5" value="75"></label><label>Notes<textarea id="futureNotes" rows="3" maxlength="1200"></textarea></label><div class="modal-actions"><button type="button" id="futureDeleteBtn" class="danger hidden">DELETE</button><span></span><button type="button" class="ghost" data-future-close>CANCEL</button><button type="submit" class="primary">SAVE FUTURE</button></div></form></dialog>`}
function inject(){const cash=$('.cash-panel');if(cash&&!$('#allowanceFuturesPanel'))cash.insertAdjacentHTML('afterend',panelHtml());if(!$('#futureDialog'))document.body.insertAdjacentHTML('beforeend',dialogHtml());}
function openFuture(row=null){const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());$('#futureId').value=row?.id||'';$('#futureDialogTitle').textContent=row?'Edit Future Expense':'Future Expense';$('#futureTitle').value=row?.title||'';$('#futureAmount').value=row?.amount??'';$('#futureDate').min=today;$('#futureDate').value=row?.dueDate||today;$('#futureCategory').value=row?.category||'OTHER';$('#futureCertainty').value=row?.certainty||'PLANNED';$('#futureProbability').value=row?.probability??(row?.certainty==='COMMITTED'?100:row?.certainty==='POSSIBLE'?40:75);$('#futureProbabilityValue').textContent=`${$('#futureProbability').value}%`;$('#futureNotes').value=row?.notes||'';$('#futureDeleteBtn').classList.toggle('hidden',!row);$('#futureDialog').showModal();}
function renderCurve(x){const svg=$('#futureCurve');if(!svg)return;const pts=[{date:new Date(),balance:x.spotRemaining},...x.rows.map(r=>({date:new Date(`${r.dueDate}T12:00:00+08:00`),balance:0,expected:r.expectedValue}))].sort((a,b)=>a.date-b.date);let bal=x.spotRemaining;for(let i=1;i<pts.length;i++){bal-=pts[i].expected||0;pts[i].balance=bal;}const ys=pts.map(p=>p.balance),min=Math.min(0,...ys),max=Math.max(1,...ys),span=Math.max(1,max-min),n=Math.max(1,pts.length-1);const coords=pts.map((p,i)=>`${(i/n)*1000},${200-((p.balance-min)/span)*170}`).join(' ');const zeroY=200-((0-min)/span)*170;svg.innerHTML=`<line x1="0" y1="${zeroY}" x2="1000" y2="${zeroY}" class="futures-zero"/><polyline points="${coords}" class="futures-line"/>${pts.map((p,i)=>`<circle cx="${(i/n)*1000}" cy="${200-((p.balance-min)/span)*170}" r="5" class="futures-dot"><title>${esc(i?pts[i].date.toLocaleDateString('en-SG'):'SPOT')} // ${esc(money(p.balance))}</title></circle>`).join('')}`;}
function render(){if(!$('#allowanceFuturesPanel'))return;const x=futuresSnapshot();$('#futureSpot').textContent=money(x.spotRemaining);$('#futureExpected').textContent=money(x.expectedFutureOutflow);$('#futureProjected').textContent=money(x.projectedRemaining);$('#futureProjected').dataset.band=x.projectedRemaining<0?'bad':x.futuresIndex<40?'watch':'good';$('#futureSpotIndex').textContent=`${Math.round(x.spotIndex)}`;$('#futureFuturesIndex').textContent=`${Math.round(x.futuresIndex)}`;$('#futureSummary').textContent=futuresSummary();renderCurve(x);const total=x.rows.length,pages=Math.max(1,Math.ceil(total/PAGE_SIZE));page=Math.min(page,pages-1);const slice=x.rows.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE),root=$('#futureRecords');root.replaceChildren();if(!slice.length)root.innerHTML='<div class="future-empty">NO FUTURE EXPENSES // ADD EXPECTED OUTFLOWS WITHOUT ALTERING SPOT BALANCE</div>';for(const r of slice){const row=document.createElement('button');row.type='button';row.className='future-record';row.innerHTML=`<span><b>${esc(r.title)}</b><small>${esc(r.category)} // ${esc(r.certainty)}</small></span><span><b>${esc(money(r.amount))}</b><small>EXPECTED ${esc(money(r.expectedValue))}</small></span><span><b>${esc(r.dueDate)}</b><small>${Math.round(probability(r)*100)}% PROB.</small></span>`;row.onclick=()=>openFuture(r);root.append(row);}$('#futurePager').textContent=total?`${page+1} / ${pages}`:'0 / 0';$('#futurePrev').disabled=page<=0;$('#futureNext').disabled=page>=pages-1;}
function bind(){
  $('#futureAddBtn').onclick=()=>openFuture();$('#futurePrev').onclick=()=>{page=Math.max(0,page-1);render();};$('#futureNext').onclick=()=>{page++;render();};document.querySelectorAll('[data-future-close]').forEach(b=>b.onclick=()=>$('#futureDialog').close());$('#futureProbability').oninput=()=>$('#futureProbabilityValue').textContent=`${$('#futureProbability').value}%`;$('#futureCertainty').onchange=()=>{const c=$('#futureCertainty').value,p=$('#futureProbability');if(c==='COMMITTED')p.value=100;else if(c==='PLANNED'&&Number(p.value)===100)p.value=75;else if(c==='POSSIBLE'&&Number(p.value)>75)p.value=40;$('#futureProbabilityValue').textContent=`${p.value}%`;};
  $('#futureForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#futureId').value||uid(),all=rows(),rec={id,title:$('#futureTitle').value.trim(),amount:Math.abs(Number($('#futureAmount').value)||0),dueDate:$('#futureDate').value,category:$('#futureCategory').value,certainty:$('#futureCertainty').value,probability:Number($('#futureProbability').value),notes:$('#futureNotes').value.trim(),updatedAt:new Date().toISOString()};if(!rec.title||!rec.amount||!rec.dueDate)return notify('Future expense needs title, amount and due date.',true);const i=all.findIndex(x=>x.id===id);if(i>=0)all[i]=rec;else all.push(rec);save(all);page=0;$('#futureDialog').close();render();notify('ALLOWANCE FUTURE SAVED');});
  $('#futureDeleteBtn').onclick=()=>{const id=$('#futureId').value;if(!id||!confirm('Delete this future expense?'))return;save(rows().filter(x=>x.id!==id));$('#futureDialog').close();render();notify('ALLOWANCE FUTURE DELETED');};
  window.addEventListener('neon:phase9a-contextchange',render);setInterval(render,60000);
}
export function initAllowanceFutures(onNotify){notify=onNotify||notify;inject();bind();render();return{snapshot:futuresSnapshot,summary:futuresSummary,render};}
export function refreshAllowanceFutures(){render();}
