import { api } from './api.js';
import { state } from './state.js';

const $=s=>document.querySelector(s);
let notify=()=>{},followups=new Map(),dialogBound=false,recognition=null,voiceActive=false,currentMailId=null;
const pad=n=>String(n).padStart(2,'0');
function localInput(iso){if(!iso)return'';const d=new Date(iso);return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function iso(v){return v?new Date(v).toISOString():null;}
function taskById(id){return (state.tasks||[]).find(t=>String(t.id)===String(id));}
function injectFollowupFields(){const form=$('#taskForm');if(!form||$('#p91TaskFollowup'))return;const notes=$('#taskNotes')?.closest('label');const fs=document.createElement('fieldset');fs.id='p91TaskFollowup';fs.className='p91-followup-fieldset';fs.innerHTML=`<legend>Follow-up / Progress Check</legend><label class="p91-checkline"><input id="p91FollowEnabled" type="checkbox"> FOLLOW UP WITH PROGRESS CHECK</label><div id="p91FollowFields" class="p91-follow-fields hidden"><div class="two"><label>Check-in frequency<select id="p91FollowFrequency"><option value="DAILY">DAILY</option><option value="EVERY_2_DAYS">EVERY 2 DAYS</option><option value="WEEKLY">WEEKLY</option><option value="CUSTOM">CUSTOM</option></select></label><label id="p91FollowIntervalWrap" class="hidden">Custom interval (hours)<input id="p91FollowInterval" type="number" min="1" max="8760" value="24"></label></div><label>First check-in<input id="p91FollowFirst" type="datetime-local"></label><div class="two"><label class="p91-checkline"><input id="p91FollowMail" type="checkbox" checked> SEND CHECK-INS TO MAILBOX</label><label class="p91-checkline"><input id="p91FollowNexus" type="checkbox" checked> ALLOW NEXUS PROGRESS TRACKING</label></div><div id="p91FollowExisting" class="p91-follow-existing"></div></div>`;form.insertBefore(fs,notes||form.querySelector('.modal-actions'));
  $('#p91FollowEnabled').onchange=()=>$('#p91FollowFields').classList.toggle('hidden',!$('#p91FollowEnabled').checked);$('#p91FollowFrequency').onchange=()=>$('#p91FollowIntervalWrap').classList.toggle('hidden',$('#p91FollowFrequency').value!=='CUSTOM');
}
function defaultFirst(){const d=new Date(Date.now()+24*3600000);d.setMinutes(0,0,0);return localInput(d.toISOString());}
function populateTaskFollowup(){const id=$('#taskId')?.value||'',f=followups.get(id);$('#p91FollowEnabled').checked=!!f?.enabled;$('#p91FollowFields').classList.toggle('hidden',!f?.enabled);$('#p91FollowFrequency').value=f?.frequency||'DAILY';$('#p91FollowInterval').value=f?.intervalHours||24;$('#p91FollowIntervalWrap').classList.toggle('hidden',(f?.frequency||'DAILY')!=='CUSTOM');$('#p91FollowFirst').value=localInput(f?.nextCheckAt)||defaultFirst();$('#p91FollowMail').checked=f?.mailEnabled!==false;$('#p91FollowNexus').checked=f?.nexusTracking!==false;const meta=$('#p91FollowExisting');meta.textContent=f?`PROGRESS ${f.percentComplete||0}% // NEXT ${f.nextCheckAt?new Date(f.nextCheckAt).toLocaleString('en-SG',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}):'UNSCHEDULED'}`:'NO FOLLOW-UP PROFILE';}
function observeTaskDialog(){const d=$('#taskDialog');if(!d||dialogBound)return;dialogBound=true;const obs=new MutationObserver(()=>{if(d.open)populateTaskFollowup();});obs.observe(d,{attributes:true,attributeFilter:['open']});}
function snapshotFollowup(){const freq=$('#p91FollowFrequency').value;return{enabled:$('#p91FollowEnabled').checked,frequency:freq,intervalHours:freq==='CUSTOM'?Number($('#p91FollowInterval').value)||24:freq==='WEEKLY'?168:freq==='EVERY_2_DAYS'?48:24,nextCheckAt:iso($('#p91FollowFirst').value),mailEnabled:$('#p91FollowMail').checked,nexusTracking:$('#p91FollowNexus').checked,title:$('#taskTitle').value.trim(),dueAt:iso($('#taskDue').value),existingId:$('#taskId').value||''};}
async function syncFollowupAfterCoreSave(snap){let taskId=snap.existingId;if(!taskId){for(let i=0;i<20&&!taskId;i++){await new Promise(r=>setTimeout(r,120));const candidates=(state.tasks||[]).filter(t=>String(t.title||'').trim()===snap.title).sort((a,b)=>String(b.createdAt||b.updatedAt||'').localeCompare(String(a.createdAt||a.updatedAt||'')));taskId=candidates[0]?.id||'';}}if(!taskId)return;try{if(!snap.enabled){if(followups.has(taskId)){await api(`/api/v8/phase9b1/task-followups/${encodeURIComponent(taskId)}`,{method:'DELETE'});followups.delete(taskId);}return;}const due=snap.dueAt||taskById(taskId)?.dueAt||null,d=await api(`/api/v8/phase9b1/task-followups/${encodeURIComponent(taskId)}`,{method:'PUT',body:{enabled:true,frequency:snap.frequency,intervalHours:snap.intervalHours,nextCheckAt:snap.nextCheckAt,originalDueAt:followups.get(taskId)?.originalDueAt||due,currentDueAt:due,mailEnabled:snap.mailEnabled,nexusTracking:snap.nexusTracking}});followups.set(taskId,d.item);window.dispatchEvent(new CustomEvent('neon:phase9b1-mail-refresh'));window.dispatchEvent(new CustomEvent('neon:phase9b1-contextchange'));}catch(e){notify(`FOLLOW-UP SAVE // ${e.message}`,true);}}
function interceptTaskSubmit(){const form=$('#taskForm');if(!form)return;form.addEventListener('submit',()=>{const snap=snapshotFollowup();setTimeout(()=>syncFollowupAfterCoreSave(snap),0);},true);}
function injectCheckinDialog(){if($('#p91CheckinDialog'))return;const d=document.createElement('dialog');d.id='p91CheckinDialog';d.className='modal p91-checkin-dialog';d.innerHTML=`<form id="p91CheckinForm" method="dialog"><input id="p91CheckinTaskId" type="hidden"><div class="modal-head"><div><span class="kicker">TASK // PROGRESS CONTROL</span><h2 id="p91CheckinTitle">Progress Check</h2></div><button type="button" class="x" id="p91CheckinClose">×</button></div><div class="p91-progress-block"><div class="p91-progress-label"><span>COMPLETION</span><b id="p91ProgressValue">0%</b></div><input id="p91Progress" type="range" min="0" max="100" step="1" value="0"><div class="p91-progress-scale"><span>0%</span><span>50%</span><span>100%</span></div></div><div class="p91-checkin-grid"><div><span>ORIGINAL DUE DATE</span><b id="p91OriginalDue">—</b></div><div><span>CURRENT DUE DATE</span><b id="p91CurrentDue">—</b></div><div><span>PREVIOUS CHECK-IN</span><b id="p91PreviousProgress">—</b></div></div><div class="two"><label>Estimated time remaining (hours)<input id="p91EtaHours" type="number" min="0" max="8760" step="0.25" placeholder="2.5"></label><label>Projected completion<input id="p91ProjectedDue" type="datetime-local"></label></div><fieldset class="p91-due-choice"><legend>If projected completion changes the deadline</legend><label><input type="radio" name="p91DueUpdate" value="no" checked> KEEP CURRENT TASK DUE DATE</label><label><input type="radio" name="p91DueUpdate" value="yes"> UPDATE TASK DUE DATE TO PROJECTED DATE</label></fieldset><label>Progress update<div class="p91-note-compose"><textarea id="p91CheckinNote" rows="6" maxlength="8000" placeholder="What changed, what remains, blockers, next action…"></textarea><button id="p91CheckinVoice" type="button" class="p91-hold-mic" aria-label="Hold to dictate progress update">MIC</button></div></label><div id="p91VoiceState" class="p91-voice-state">VOICE // HOLD TO SPEAK WHEN SUPPORTED</div><details class="p91-checkin-history"><summary>Progress history</summary><div id="p91CheckinHistory"></div></details><div class="modal-actions"><span></span><span></span><button type="button" id="p91CheckinCancel" class="ghost">CANCEL</button><button type="submit" class="primary">SUBMIT CHECK-IN</button></div></form>`;document.body.append(d);$('#p91CheckinClose').onclick=$('#p91CheckinCancel').onclick=()=>d.close();$('#p91Progress').oninput=()=>$('#p91ProgressValue').textContent=`${$('#p91Progress').value}%`;$('#p91CheckinForm').onsubmit=submitCheckin;bindVoice();}
function fmtDue(iso){return iso?new Date(iso).toLocaleString('en-SG',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}):'NONE';}
async function openCheckin(taskId,mailId=null){const f=followups.get(taskId),task=taskById(taskId);if(!f){notify('FOLLOW-UP PROFILE NOT FOUND',true);return;}currentMailId=mailId;$('#p91CheckinTaskId').value=taskId;$('#p91CheckinTitle').textContent=task?.title||'Progress Check';$('#p91Progress').value=f.percentComplete||0;$('#p91ProgressValue').textContent=`${f.percentComplete||0}%`;$('#p91OriginalDue').textContent=fmtDue(f.originalDueAt);$('#p91CurrentDue').textContent=fmtDue(task?.dueAt||f.currentDueAt);$('#p91EtaHours').value=f.etaMinutes==null?'':(Number(f.etaMinutes)/60).toFixed(2).replace(/\.00$/,'');$('#p91ProjectedDue').value=localInput(f.projectedDueAt||task?.dueAt||f.currentDueAt);$('#p91CheckinNote').value='';const hist=await api(`/api/v8/phase9b1/task-followups/${encodeURIComponent(taskId)}/checkins`).catch(()=>({items:[]})),rows=hist.items||[];$('#p91PreviousProgress').textContent=rows.length?`${rows[0].percentComplete}%`:'NO HISTORY';$('#p91CheckinHistory').innerHTML=rows.length?rows.slice(0,12).map(x=>`<div class="p91-history-row"><time>${esc(new Date(x.createdAt).toLocaleString('en-SG',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}))}</time><b>${x.percentComplete}%</b><span>${x.etaMinutes==null?'ETA —':`ETA ${(x.etaMinutes/60).toFixed(1)}H`}</span><p>${esc(x.note||'')}</p></div>`).join(''):'<div class="p91-empty">NO CHECK-INS YET</div>';$('#p91CheckinDialog').showModal();}
async function submitCheckin(e){e.preventDefault();const taskId=$('#p91CheckinTaskId').value,f=followups.get(taskId),projected=iso($('#p91ProjectedDue').value),update=document.querySelector('input[name="p91DueUpdate"]:checked')?.value==='yes',etaHours=Number($('#p91EtaHours').value),body={percentComplete:Number($('#p91Progress').value),etaMinutes:Number.isFinite(etaHours)?Math.round(etaHours*60):null,projectedDueAt:projected,updateTaskDue:update,note:$('#p91CheckinNote').value.trim()};try{await api(`/api/v8/phase9b1/task-followups/${encodeURIComponent(taskId)}/checkins`,{method:'POST',body});if(update&&projected){const out=await api(`/api/v8/tasks/${encodeURIComponent(taskId)}`,{method:'PATCH',body:{dueAt:projected}});const i=(state.tasks||[]).findIndex(t=>t.id===taskId);if(i>=0)state.tasks[i]={...state.tasks[i],...out.item};}await refresh();if(currentMailId)await api(`/api/v8/phase9b1/mail/${encodeURIComponent(currentMailId)}`,{method:'PATCH',body:{status:'READ'}}).catch(()=>{});$('#p91CheckinDialog').close();window.dispatchEvent(new CustomEvent('neon:phase9b1-mail-refresh'));window.dispatchEvent(new CustomEvent('neon:phase9b1-contextchange'));notify('TASK PROGRESS CHECK-IN SAVED');}catch(err){notify(err.message,true);}}
function bindVoice(){const btn=$('#p91CheckinVoice'),stateEl=$('#p91VoiceState'),SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){btn.disabled=true;stateEl.textContent='VOICE // BROWSER SPEECH RECOGNITION UNAVAILABLE — KEYBOARD READY';return;}const start=()=>{if(voiceActive)return;recognition=new SR();recognition.continuous=true;recognition.interimResults=true;recognition.lang='en-SG';let committed='';recognition.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)committed+=`${t} `;else interim+=t;}const ta=$('#p91CheckinNote');if(committed.trim()){const base=ta.dataset.voiceBase||ta.value;ta.value=`${base}${base&& !base.endsWith(' ')?' ':''}${committed}`.trimStart();ta.dataset.voiceBase=ta.value;committed='';}stateEl.textContent=`VOICE // ${interim||'LISTENING'}`;};recognition.onerror=e=>{stateEl.textContent=`VOICE // ${String(e.error||'ERROR').toUpperCase()}`;stop();};recognition.onend=()=>{voiceActive=false;btn.classList.remove('active');stateEl.textContent='VOICE // READY';};$('#p91CheckinNote').dataset.voiceBase=$('#p91CheckinNote').value;voiceActive=true;btn.classList.add('active');stateEl.textContent='VOICE // LISTENING';try{recognition.start();}catch{}};const stop=()=>{if(!voiceActive)return;voiceActive=false;btn.classList.remove('active');try{recognition?.stop();}catch{}};btn.addEventListener('pointerdown',e=>{e.preventDefault();btn.setPointerCapture?.(e.pointerId);start();});btn.addEventListener('pointerup',stop);btn.addEventListener('pointercancel',stop);btn.addEventListener('lostpointercapture',stop);}
async function refresh(){try{const d=await api('/api/v8/phase9b1/task-followups');followups=new Map((d.items||[]).map(x=>[String(x.taskId),x]));if($('#taskDialog')?.open)populateTaskFollowup();window.dispatchEvent(new CustomEvent('neon:phase9b1-contextchange'));}catch(e){console.warn('P91 followups unavailable',e);}}
export function followupSnapshot(){return[...followups.values()].filter(x=>x.nexusTracking!==false).map(x=>{const t=taskById(x.taskId);return{taskId:x.taskId,title:t?.title||'',status:t?.status||'',priority:t?.priority||'',percentComplete:x.percentComplete,etaMinutes:x.etaMinutes,originalDueAt:x.originalDueAt,currentDueAt:t?.dueAt||x.currentDueAt,projectedDueAt:x.projectedDueAt,nextCheckAt:x.nextCheckAt};});}
export async function initPhase9B1Tasks(onNotify){notify=onNotify||notify;injectFollowupFields();injectCheckinDialog();observeTaskDialog();interceptTaskSubmit();await refresh();window.addEventListener('neon:phase9b1-task-checkin',e=>openCheckin(String(e.detail?.taskId||''),e.detail?.mailId||null));return{refresh,openCheckin,followupSnapshot};}
