import { api } from './api.js';
import { initPhase9B1Tasks,followupSnapshot } from './phase9b1-tasks.js';
const $=s=>document.querySelector(s);
let statusMap=new Map();
function fmt(v){if(!v)return'—';try{return new Date(v).toLocaleString('en-SG',{timeZone:'Asia/Singapore',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false})+' SGT';}catch{return String(v)}}
async function loadSchedulerStatus(){try{const d=await api('/api/v8/phase9c/scheduler/status');statusMap=new Map((d.items||[]).map(x=>[String(x.task_id||x.taskId),x]));renderSchedulerTelemetry();}catch(e){console.warn('9C scheduler status unavailable',e);}}
function ensureTelemetry(){const fs=$('#p91TaskFollowup');if(!fs||$('#p9cFollowTelemetry'))return;const box=document.createElement('div');box.id='p9cFollowTelemetry';box.className='p9c-follow-telemetry';box.innerHTML='<div><span>STATUS</span><b id="p9cFollowStatus">—</b></div><div><span>NEXT CHECK</span><b id="p9cFollowNext">—</b></div><div><span>LAST FIRED</span><b id="p9cFollowLast">—</b></div><div><span>DELIVERY</span><b id="p9cFollowDelivery">MAIL + NEXUS</b></div>';fs.append(box);}
function renderSchedulerTelemetry(){ensureTelemetry();const id=$('#taskId')?.value||'',r=statusMap.get(String(id));if($('#p9cFollowStatus'))$('#p9cFollowStatus').textContent=r?.status||($('#p91FollowEnabled')?.checked?'PENDING SAVE':'DISABLED');if($('#p9cFollowNext'))$('#p9cFollowNext').textContent=fmt(r?.next_check_at||$('#p91FollowFirst')?.value);if($('#p9cFollowLast'))$('#p9cFollowLast').textContent=fmt(r?.last_delivered_at);if($('#p9cFollowDelivery'))$('#p9cFollowDelivery').textContent=`${$('#p91FollowMail')?.checked!==false?'MAIL':''}${$('#p91FollowNexus')?.checked!==false?' + NEXUS':''}`.replace(/^ \+ /,'')||'INTERNAL';}
function bind(){const d=$('#taskDialog');if(d)new MutationObserver(()=>{if(d.open){ensureTelemetry();loadSchedulerStatus();}}).observe(d,{attributes:true,attributeFilter:['open']});document.addEventListener('change',e=>{if(e.target?.closest?.('#p91TaskFollowup'))renderSchedulerTelemetry();});window.addEventListener('neon:phase9b1-mail-refresh',loadSchedulerStatus);}
export async function initPhase9CTasks(notify){const core=await initPhase9B1Tasks(notify);ensureTelemetry();bind();await loadSchedulerStatus();return{...core,refreshScheduler:loadSchedulerStatus,followupSnapshot};}
export {followupSnapshot};
