import { apiForm } from './api.js';
const $=s=>document.querySelector(s);
let recorder=null,stream=null,chunks=[],startedAt=0,busy=false,timer=null;
const editable=t=>!!t?.closest?.('input,textarea,select,button,[contenteditable="true"],[role="textbox"]');
function active(){return !!$('#pageNexus')?.classList.contains('active');}
function hud(){let x=$('#p9d2SpaceVoice');if(x)return x;const host=$('#nexusComposer')?.parentElement;if(!host)return null;x=document.createElement('div');x.id='p9d2SpaceVoice';x.className='p9d2-space-voice';x.innerHTML='<span class="p9d2-space-key">SPACE</span><b id="p9d2SpaceState">START RECORDING</b><small id="p9d2SpaceTime">SPACE #1 RECORD // SPACE #2 END + TRANSCRIBE</small>';host.append(x);return x;}
function state(text,mode='ready',sub=''){const h=hud(),b=$('#p9d2SpaceState'),s=$('#p9d2SpaceTime');if(h)h.dataset.state=mode;if(b)b.textContent=text;if(s)s.textContent=sub||'SPACE #1 RECORD // SPACE #2 END + TRANSCRIBE';}
function supportedMime(){for(const m of ['audio/webm;codecs=opus','audio/mp4','audio/webm','audio/ogg;codecs=opus'])if(window.MediaRecorder?.isTypeSupported?.(m))return m;return'';}
function stopTracks(){for(const t of stream?.getTracks?.()||[])try{t.stop()}catch{}stream=null;clearInterval(timer);timer=null;}
function reset(){recorder=null;chunks=[];startedAt=0;busy=false;stopTracks();state('START RECORDING','ready');}
async function start(){if(busy||recorder?.state==='recording')return;if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){state('MIC UNAVAILABLE','error','BROWSER MEDIARECORDER REQUIRED');return;}busy=true;try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const mime=supportedMime(),opts=mime?{mimeType:mime}:{};chunks=[];recorder=new MediaRecorder(stream,opts);recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data);};recorder.onerror=()=>{state('RECORDING ERROR','error');reset();};recorder.start(250);startedAt=Date.now();busy=false;state('RECORDING','recording','SPACE #2 // END + TRANSCRIBE');timer=setInterval(()=>{const sec=Math.floor((Date.now()-startedAt)/1000),m=String(Math.floor(sec/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');const e=$('#p9d2SpaceTime');if(e)e.textContent=`${m}:${s} // SPACE #2 END + TRANSCRIBE`;},250);}catch(e){reset();state('MIC PERMISSION REQUIRED','error',e.message||'ALLOW MICROPHONE ACCESS');}}
async function stop(){if(busy||recorder?.state!=='recording')return;busy=true;state('ENDING RECORDING','busy','PREPARING AUDIO…');const r=recorder;const blob=await new Promise(resolve=>{r.addEventListener('stop',()=>resolve(new Blob(chunks,{type:r.mimeType||'audio/webm'})),{once:true});try{r.stop()}catch{resolve(new Blob(chunks,{type:r.mimeType||'audio/webm'}));}});stopTracks();if(!blob.size){reset();state('NO AUDIO CAPTURED','error');return;}state('TRANSCRIBING','busy','NEXUS // SPEECH → TEXT');try{const fd=new FormData();fd.append('audio',new File([blob],'nexus-space-recording',{type:blob.type||'audio/webm'}));const out=await apiForm('/api/v8/nexus/transcribe',fd);const text=String(out.transcript||'').trim();if(!text)throw new Error('No speech detected');const ta=$('#nexusInput');if(!ta)throw new Error('NEXUS composer unavailable');ta.value=text;ta.dispatchEvent(new Event('input',{bubbles:true}));state('TRANSCRIBED','ready',`“${text.slice(0,90)}${text.length>90?'…':''}”`);setTimeout(()=>$('#nexusComposer')?.requestSubmit?.(),120);}catch(e){state('TRANSCRIPTION FAILED','error',e.message||'TRY AGAIN');}finally{busy=false;recorder=null;chunks=[];startedAt=0;}}
function onKey(e){if(e.code!=='Space'||e.repeat||!active()||editable(e.target))return;e.preventDefault();e.stopPropagation();if(recorder?.state==='recording')stop();else start();}
export function initPhase9D2Nexus(){hud();document.addEventListener('keydown',onKey,true);return{start,stop,destroy(){document.removeEventListener('keydown',onKey,true);reset();}};}
