import { api } from './api.js';
import { state } from './state.js';
import { refreshFinance as refreshCoreFinance } from './finance.js';

const $=s=>document.querySelector(s);
let notify=()=>{},contexts=new Map(),searchTimer=null,pendingInstrument=null,positionDialogBound=false,quoteTimer=null,quoteBusy=false;
const pad=n=>String(n).padStart(2,'0');
function money(v){const c=state.finance?.settings?.currency||'SGD';try{return new Intl.NumberFormat('en-SG',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v)||0)}catch{return`${c} ${(Number(v)||0).toFixed(2)}`}}
function pct(v){const n=Number(v)||0;return`${n>=0?'+':''}${n.toFixed(1)}%`;}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function now(){return Date.now();}
function futures(){try{return window.NeonPhase9A?.futuresSnapshot?.()||null}catch{return null}}
function tx(){return[...(state.finance?.transactions||[])].sort((a,b)=>new Date(a.occurredAt)-new Date(b.occurredAt));}
function allowanceAnalytics(){const f=state.finance||{},base=Number(f.settings?.startingBalance)||0,rows=tx(),inflows=rows.filter(x=>x.direction==='inflow').reduce((s,x)=>s+Math.abs(Number(x.amount)||0),0),expenses=rows.filter(x=>x.direction==='expense').reduce((s,x)=>s+Math.abs(Number(x.amount)||0),0),remaining=base+inflows-expenses,nowMs=now(),spendIn=days=>rows.filter(x=>x.direction==='expense'&&nowMs-new Date(x.occurredAt).getTime()<=days*86400000).reduce((s,x)=>s+Math.abs(Number(x.amount)||0),0),spend7=spendIn(7),spend30=spendIn(30),burn7=spend7/7,burn30=spend30/30,reference=Math.max(1,base+inflows),decay=(1-remaining/reference)*100;let bal=base,peak=base,maxDd=0;for(const r of rows){bal+=r.direction==='inflow'?Math.abs(Number(r.amount)||0):-Math.abs(Number(r.amount)||0);peak=Math.max(peak,bal);if(peak>0)maxDd=Math.min(maxDd,(bal-peak)/peak*100);}const daily=new Map();for(const r of rows){if(r.direction!=='expense')continue;const d=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(r.occurredAt));daily.set(d,(daily.get(d)||0)+Math.abs(Number(r.amount)||0));}const last30=[];for(let i=29;i>=0;i--){const d=new Date(nowMs-i*86400000),k=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);last30.push(daily.get(k)||0);}const mean=last30.reduce((a,b)=>a+b,0)/30,variance=last30.reduce((a,b)=>a+(b-mean)**2,0)/30,volatility=Math.sqrt(variance),velocity=burn30>0?(burn7/burn30-1)*100:0,cats={};for(const r of rows.filter(x=>x.direction==='expense'&&nowMs-new Date(x.occurredAt).getTime()<=30*86400000)){const k=r.category||'Other';cats[k]=(cats[k]||0)+Math.abs(Number(r.amount)||0);}const topCat=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0],concentration=spend30>0?(topCat?.[1]||0)/spend30*100:0,fs=futures(),projected=fs?.projectedRemaining??remaining,blend=burn7>0&&burn30>0?burn7*.65+burn30*.35:burn7||burn30,runway=blend>0?projected/blend:null,next30Future=fs?.rows?.filter(r=>{const t=new Date(`${r.dueDate}T23:59:59+08:00`).getTime()-nowMs;return t>=0&&t<=30*86400000;}).reduce((s,r)=>s+Number(r.expectedValue||0),0)||0,forecastDelta=spend30?((next30Future-spend30)/spend30)*100:0;return{remaining,burn7,burn30,decay,maxDrawdown:maxDd,velocity,volatility,runway,concentration,topCategory:topCat?.[0]||'—',projected,futureExposure:fs?.expectedFutureOutflow||0,forecastDelta};}
function injectAllowanceIndicators(){const cash=$('.cash-panel');if(!cash||$('#p91AllowanceIndicators'))return;const bar=$('#p9AllowanceModebar')||cash.querySelector(':scope > .panel-head'),el=document.createElement('section');el.id='p91AllowanceIndicators';el.className='p91-allowance-intel';el.innerHTML=`<div class="p91-indicator-head"><div><span class="kicker">ALLOWANCE // INTELLIGENCE</span><h3>Decay, Burn & Runway</h3></div><span id="p91AllowanceState" class="p91-mini-state">LIVE</span></div><div class="p91-indicator-grid"><div><span>7D BURN</span><b id="p91Burn7">—</b></div><div><span>30D BURN</span><b id="p91Burn30">—</b></div><div><span>DECAY</span><b id="p91Decay">—</b></div><div><span>MAX DRAWDOWN</span><b id="p91Drawdown">—</b></div><div><span>RUNWAY</span><b id="p91Runway">—</b></div><div><span>SPEND VELOCITY</span><b id="p91Velocity">—</b></div><div><span>SPEND VOLATILITY</span><b id="p91Volatility">—</b></div><div><span>TOP CATEGORY</span><b id="p91Concentration">—</b></div><div><span>FUTURES EXPOSURE</span><b id="p91FutureExposure">—</b></div><div><span>PROJECTED BALANCE</span><b id="p91ProjectedBalance">—</b></div></div>`;bar.insertAdjacentElement('afterend',el);renderAllowanceIndicators();}
function renderAllowanceIndicators(){if(!$('#p91AllowanceIndicators'))return;const a=allowanceAnalytics();$('#p91Burn7').textContent=`${money(a.burn7)} / DAY`;$('#p91Burn30').textContent=`${money(a.burn30)} / DAY`;$('#p91Decay').textContent=`${Math.max(0,a.decay).toFixed(1)}%`;$('#p91Drawdown').textContent=`${a.maxDrawdown.toFixed(1)}%`;$('#p91Runway').textContent=a.runway==null?'—':a.runway>999?'999+ DAYS':`${Math.max(0,a.runway).toFixed(1)} DAYS`;$('#p91Velocity').textContent=pct(a.velocity);$('#p91Velocity').dataset.band=a.velocity>25?'bad':a.velocity>8?'watch':'good';$('#p91Volatility').textContent=money(a.volatility);$('#p91Concentration').textContent=`${esc(a.topCategory)} // ${a.concentration.toFixed(0)}%`;$('#p91FutureExposure').textContent=money(a.futureExposure);$('#p91ProjectedBalance').textContent=money(a.projected);$('#p91ProjectedBalance').dataset.band=a.projected<0?'bad':a.projected<a.remaining*.5?'watch':'good';}

function assetType(instr){const t=String(instr?.instrumentType||'').toLowerCase(),s=String(instr?.symbol||'');if(/commodity|precious|metal|energy/.test(t)||/XAU|XAG|WTI|BRENT/i.test(s))return'COMMODITY';if(/forex|currency/.test(t)||s.includes('/'))return'FX';if(/crypto/.test(t))return'CRYPTO';if(/etf|fund/.test(t))return'ETF';if(/stock|equity|common/.test(t))return'EQUITY';if(/bond|fixed/.test(t))return'BOND';return'OTHER';}
function tvSymbol(instr){const symbol=String(instr?.symbol||'').toUpperCase();if(symbol==='XAU/USD')return'OANDA:XAUUSD';if(symbol==='XAG/USD')return'OANDA:XAGUSD';if(assetType(instr)==='FX')return symbol.replace('/','');const ex=String(instr?.exchange||'').toUpperCase().replace(/[^A-Z0-9_]/g,'');return ex?`${ex}:${symbol.replace('/','')}`:symbol.replace('/','');}
function injectPositionIntelligence(){const form=$('#positionForm');if(!form||$('#p91InstrumentSearch'))return;const firstTwo=form.querySelector('.two');const fs=document.createElement('fieldset');fs.id='p91InstrumentSearch';fs.className='p91-instrument-fieldset';fs.innerHTML=`<legend>Live Instrument Resolver</legend><div class="p91-instrument-search"><input id="p91InstrumentQuery" type="search" autocomplete="off" placeholder="Search gold, XAUUSD, Apple, NVDA…"><button id="p91InstrumentSearchBtn" type="button" class="ghost">SEARCH</button></div><div id="p91InstrumentResults" class="p91-instrument-results hidden"></div><div id="p91InstrumentSelected" class="p91-instrument-selected">MANUAL POSITION // SEARCH TO RESOLVE SYMBOL + METADATA</div></fieldset>`;form.insertBefore(fs,firstTwo);const sector=$('#positionSector')?.closest('label'),extra=document.createElement('fieldset');extra.id='p91PositionContext';extra.className='p91-position-context';extra.innerHTML=`<legend>Intelligence Context</legend><label>Description<textarea id="p91PositionDescription" rows="2" maxlength="2400" placeholder="Investment thesis / role of this position…"></textarea></label><label>Custom relevance keywords<input id="p91PositionKeywords" maxlength="1200" placeholder="Fed, real yields, DXY, Middle East…"></label><div class="two"><label>TradingView symbol<input id="p91TradingViewSymbol" maxlength="120" placeholder="OANDA:XAUUSD"></label><label>Current-price mode<select id="p91PriceMode"><option value="AUTO">AUTO // TWELVE DATA</option><option value="MANUAL">MANUAL OVERRIDE</option></select></label></div><div class="p91-price-line"><span id="p91QuoteSource">QUOTE // NOT LOADED</span><button id="p91RefreshQuote" type="button" class="ghost small">REFRESH QUOTE</button></div></fieldset>`;sector?.insertAdjacentElement('afterend',extra);$('#p91InstrumentSearchBtn').onclick=searchInstruments;$('#p91InstrumentQuery').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(searchInstruments,350);};$('#p91RefreshQuote').onclick=refreshCurrentQuote;$('#p91PriceMode').onchange=syncPriceMode;}
async function searchInstruments(){const q=$('#p91InstrumentQuery')?.value.trim();if(!q)return;const root=$('#p91InstrumentResults');root.classList.remove('hidden');root.innerHTML='<div class="p91-empty">SEARCHING TWELVE DATA…</div>';try{const d=await api(`/api/v8/phase9b1/instruments/search?q=${encodeURIComponent(q)}`),rows=d.items||[];root.replaceChildren();if(!rows.length){root.innerHTML='<div class="p91-empty">NO INSTRUMENT MATCHES</div>';return;}for(const x of rows){const b=document.createElement('button');b.type='button';b.className='p91-instrument-row';b.innerHTML=`<span><b>${esc(x.symbol)}</b><strong>${esc(x.name||'')}</strong></span><span>${esc(x.exchange||'—')}<small>${esc(x.instrumentType||'')}</small></span><span>${esc(x.currency||'—')}</span>`;b.onclick=()=>selectInstrument(x);root.append(b);}}catch(e){root.innerHTML=`<div class="p91-empty">${esc(e.message)}</div>`;}}
async function selectInstrument(x){pendingInstrument=x;$('#positionSymbol').value=x.symbol||'';$('#positionAssetType').value=assetType(x);if(!$('#positionSector').value)$('#positionSector').value=x.instrumentType||'';$('#p91TradingViewSymbol').value=tvSymbol(x);$('#p91InstrumentSelected').innerHTML=`<b>${esc(x.symbol)}</b> // ${esc(x.name||'')} // ${esc(x.exchange||'')} // ${esc(x.currency||'')}`;$('#p91InstrumentResults').classList.add('hidden');$('#p91InstrumentQuery').value=`${x.symbol} — ${x.name||''}`;await refreshCurrentQuote();}
function syncPriceMode(){const manual=$('#p91PriceMode').value==='MANUAL',input=$('#positionCurrentPrice');input.readOnly=!manual;input.placeholder=manual?'Manual current price':'Auto quote';$('#p91RefreshQuote').disabled=manual;}
async function refreshCurrentQuote(){const symbol=$('#positionSymbol')?.value.trim();if(!symbol||$('#p91PriceMode').value==='MANUAL')return;const label=$('#p91QuoteSource');label.textContent='QUOTE // REFRESHING…';try{const d=await api(`/api/v8/phase9b1/quotes?symbols=${encodeURIComponent(symbol)}`),q=d.items?.[0];if(!q||q.error||!Number.isFinite(Number(q.price)))throw new Error(q?.error||'Quote unavailable');$('#positionCurrentPrice').value=Number(q.price);label.textContent=`TWELVE DATA // ${q.price} // ${q.fetchedAt?new Date(q.fetchedAt).toLocaleTimeString('en-SG',{hour:'2-digit',minute:'2-digit',hour12:false}):'LIVE'}`;label.dataset.source='live';const id=$('#positionId').value;if(id&&contexts.has(id))contexts.set(id,{...contexts.get(id),lastQuotePrice:Number(q.price),lastQuoteAt:q.fetchedAt,quoteSource:'TWELVE_DATA'});}catch(e){label.textContent=`QUOTE // ${e.message.toUpperCase()}`;label.dataset.source='error';notify(e.message,true);}}
function contextFor(id){return contexts.get(String(id))||null;}
function resetPositionContext(){pendingInstrument=null;$('#p91InstrumentQuery').value='';$('#p91InstrumentResults').classList.add('hidden');$('#p91InstrumentSelected').textContent='MANUAL POSITION // SEARCH TO RESOLVE SYMBOL + METADATA';$('#p91PositionDescription').value='';$('#p91PositionKeywords').value='';$('#p91TradingViewSymbol').value='';$('#p91PriceMode').value='AUTO';$('#p91QuoteSource').textContent='QUOTE // NOT LOADED';syncPriceMode();}
async function populatePositionContext(){const id=$('#positionId').value||'',c=contextFor(id);resetPositionContext();if(c){pendingInstrument=c.instrument||null;$('#p91InstrumentQuery').value=c.name?`${c.symbol} — ${c.name}`:c.symbol||'';$('#p91InstrumentSelected').innerHTML=`<b>${esc(c.symbol||'')}</b> // ${esc(c.name||'')} // ${esc(c.exchange||'')} // ${esc(c.currency||'')}`;$('#p91PositionDescription').value=c.description||'';$('#p91PositionKeywords').value=(c.keywords||[]).join(', ');$('#p91TradingViewSymbol').value=c.tradingviewSymbol||'';$('#p91PriceMode').value=c.manualOverride?'MANUAL':'AUTO';$('#p91QuoteSource').textContent=c.lastQuoteAt?`${c.quoteSource||'QUOTE'} // ${c.lastQuotePrice??'—'} // ${new Date(c.lastQuoteAt).toLocaleString('en-SG',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false})}`:'QUOTE // NOT LOADED';syncPriceMode();if(!c.manualOverride)await refreshCurrentQuote();}else{const symbol=$('#positionSymbol').value;if(symbol){$('#p91InstrumentQuery').value=symbol;$('#p91TradingViewSymbol').value=symbol.replace('/','');await refreshCurrentQuote();}}}
function observePositionDialog(){const d=$('#positionDialog');if(!d||positionDialogBound)return;positionDialogBound=true;new MutationObserver(()=>{if(d.open)populatePositionContext();}).observe(d,{attributes:true,attributeFilter:['open']});}
function positionSnapshot(){const c=contextFor($('#positionId').value)||{},instr=pendingInstrument||c.instrument||{};return{existingId:$('#positionId').value||'',symbol:$('#positionSymbol').value.trim(),name:instr.name||c.name||'',exchange:instr.exchange||c.exchange||'',assetType:$('#positionAssetType').value,currency:instr.currency||c.currency||'',sector:$('#positionSector').value.trim(),description:$('#p91PositionDescription').value.trim(),notes:$('#positionNotes').value.trim(),keywords:$('#p91PositionKeywords').value.split(',').map(x=>x.trim()).filter(Boolean),instrument:instr,tradingviewSymbol:$('#p91TradingViewSymbol').value.trim(),manualOverride:$('#p91PriceMode').value==='MANUAL',lastQuotePrice:Number($('#positionCurrentPrice').value)||null,lastQuoteAt:$('#p91PriceMode').value==='MANUAL'?new Date().toISOString():(c.lastQuoteAt||new Date().toISOString()),quoteSource:$('#p91PriceMode').value==='MANUAL'?'MANUAL':($('#p91QuoteSource').dataset.source==='live'?'TWELVE_DATA':c.quoteSource||'TWELVE_DATA')};}
async function syncContextAfterCoreSave(snap){let id=snap.existingId;if(!id){for(let i=0;i<20&&!id;i++){await new Promise(r=>setTimeout(r,120));const match=(state.finance?.positions||[]).filter(p=>String(p.symbol||'').toUpperCase()===snap.symbol.toUpperCase()).at(-1);id=match?.id||'';}}if(!id)return;try{const d=await api(`/api/v8/phase9b1/positions/${encodeURIComponent(id)}/context`,{method:'PUT',body:snap});contexts.set(String(id),d.item);renderTradingViewPicker();window.dispatchEvent(new CustomEvent('neon:phase9b1-contextchange'));}catch(e){notify(`POSITION CONTEXT // ${e.message}`,true);}}
function interceptPositionSubmit(){const form=$('#positionForm');if(!form)return;form.addEventListener('submit',()=>{const snap=positionSnapshot();setTimeout(()=>syncContextAfterCoreSave(snap),0);},true);}

function injectTradingView(){const panel=$('.portfolio-analytics-panel');if(!panel||$('#p91TradingViewPanel'))return;const s=document.createElement('section');s.id='p91TradingViewPanel';s.className='p91-tradingview-card';s.innerHTML=`<div class="p91-tv-head"><div><span class="kicker">TRADINGVIEW // TECHNICAL LAYER</span><h3>Position Chart</h3></div><div class="actions"><select id="p91TvPositionSelect" aria-label="TradingView position"><option value="">SELECT POSITION</option></select><button id="p91TvLoad" type="button" class="ghost small">LOAD CHART</button></div></div><div id="p91TradingViewHost" class="p91-tv-host"><div class="p91-empty">SELECT A POSITION TO LOAD A CONTAINED TRADINGVIEW CHART.</div></div><div class="p91-tv-note">TradingView is the chart/technical-analysis layer. Neon position accounting and quote sources remain independent.</div>`;panel.append(s);$('#p91TvLoad').onclick=renderSelectedTradingView;renderTradingViewPicker();}
function renderTradingViewPicker(){const sel=$('#p91TvPositionSelect');if(!sel)return;const old=sel.value,rows=state.finance?.positions||[];sel.innerHTML='<option value="">SELECT POSITION</option>'+rows.map(p=>`<option value="${esc(p.id)}">${esc(p.symbol||p.name||p.id)}</option>`).join('');if(rows.some(p=>String(p.id)===old))sel.value=old;}
function renderSelectedTradingView(){const id=$('#p91TvPositionSelect').value,p=(state.finance?.positions||[]).find(x=>String(x.id)===id),c=contextFor(id),symbol=c?.tradingviewSymbol||String(p?.symbol||'').replace('/','');if(!symbol)return notify('SELECT A POSITION WITH A TRADINGVIEW SYMBOL',true);const host=$('#p91TradingViewHost');host.replaceChildren();const wrap=document.createElement('div');wrap.className='tradingview-widget-container';wrap.style.height='100%';wrap.style.width='100%';const inner=document.createElement('div');inner.className='tradingview-widget-container__widget';inner.style.height='calc(100% - 30px)';inner.style.width='100%';const credit=document.createElement('div');credit.className='tradingview-widget-copyright';credit.innerHTML='<a href="https://www.tradingview.com/" rel="noopener nofollow" target="_blank">Chart by TradingView</a>';const script=document.createElement('script');script.type='text/javascript';script.src='https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js';script.async=true;script.textContent=JSON.stringify({autosize:true,symbol,interval:'60',timezone:'Asia/Singapore',theme:'dark',style:'1',locale:'en',backgroundColor:'rgba(9,9,13,1)',gridColor:'rgba(255,255,255,0.04)',hide_top_toolbar:false,allow_symbol_change:true,save_image:false,calendar:false,support_host:'https://www.tradingview.com'});wrap.append(inner,credit,script);host.append(wrap);}

function canonicalSymbol(v){return String(v||'').toUpperCase().replace(/^US\./,'').replace(/[^A-Z0-9]/g,'');}
function brokerQuoteFor(symbol){const key=canonicalSymbol(symbol);for(const p of state.phase9a?.brokers?.moomoo?.positions||[]){const raw=p.code||p.symbol||'',ps=canonicalSymbol(String(raw).includes('.')?String(raw).split('.').pop():raw);if(ps!==key)continue;const price=Number(p.price??p.nominalPrice??p.nominal_price??p.marketPrice??p.market_price);if(Number.isFinite(price)&&price>0)return{price,source:'MOOMOO',fetchedAt:state.phase9a?.brokers?.moomoo?.syncedAt||new Date().toISOString()};}return null;}
async function persistAutoQuote(position,context,quote){if(!position?.id||!Number.isFinite(Number(quote?.price)))return;const price=Number(quote.price),changed=Math.abs((Number(position.currentPrice)||0)-price)>1e-10;position.currentPrice=price;try{if(changed)await api(`/api/v8/finance/positions/${encodeURIComponent(position.id)}`,{method:'PATCH',body:{currentPrice:price}});}catch(e){console.warn('P91 core quote persistence',position.symbol,e.message);}if(context){const next={...context,lastQuotePrice:price,lastQuoteAt:quote.fetchedAt||new Date().toISOString(),quoteSource:quote.source||'TWELVE_DATA',manualOverride:false};contexts.set(String(position.id),next);try{await api(`/api/v8/phase9b1/positions/${encodeURIComponent(position.id)}/context`,{method:'PUT',body:next});}catch(e){console.warn('P91 context quote persistence',position.symbol,e.message);}}}
async function refreshPortfolioQuotes({force=false}={}){if(quoteBusy)return;const rows=(state.finance?.positions||[]).filter(p=>{const c=contextFor(p.id);return p.symbol&&c?.manualOverride!==true;});if(!rows.length)return;quoteBusy=true;try{const needsTwelve=[];for(const p of rows){const c=contextFor(p.id),b=brokerQuoteFor(p.symbol);if(b)await persistAutoQuote(p,c,b);else needsTwelve.push(p);}for(let i=0;i<needsTwelve.length;i+=8){const batch=needsTwelve.slice(i,i+8),symbols=batch.map(p=>p.symbol).join(',');try{const d=await api(`/api/v8/phase9b1/quotes?symbols=${encodeURIComponent(symbols)}`),quotes=d.items||[];for(const p of batch){const q=quotes.find(x=>canonicalSymbol(x.symbol)===canonicalSymbol(p.symbol));if(q&&!q.error&&Number.isFinite(Number(q.price)))await persistAutoQuote(p,contextFor(p.id),{...q,source:'TWELVE_DATA'});}}catch(e){console.warn('P91 portfolio quote batch',e.message);}}refreshCoreFinance();renderTradingViewPicker();window.dispatchEvent(new CustomEvent('neon:phase9b1-contextchange'));}finally{quoteBusy=false;}}
async function refreshContexts(){try{const d=await api('/api/v8/phase9b1/positions/context');contexts=new Map((d.items||[]).map(x=>[String(x.positionId),x]));renderTradingViewPicker();if($('#positionDialog')?.open)populatePositionContext();}catch(e){console.warn('P91 position context unavailable',e);}}
export function financeContextSnapshot(){const a=allowanceAnalytics();return{allowance:{remaining:a.remaining,burn7PerDay:a.burn7,burn30PerDay:a.burn30,decayPct:a.decay,maxDrawdownPct:a.maxDrawdown,runwayDays:a.runway,spendVelocityPct:a.velocity,spendVolatility:a.volatility,topCategory:a.topCategory,categoryConcentrationPct:a.concentration,futureExposure:a.futureExposure,projectedBalance:a.projected},positions:(state.finance?.positions||[]).map(p=>({id:p.id,symbol:p.symbol,quantity:p.quantity,entryPrice:p.entryPrice,currentPrice:p.currentPrice,context:contextFor(p.id)||null}))};}
export async function initPhase9B1Finance(onNotify){notify=onNotify||notify;injectAllowanceIndicators();injectPositionIntelligence();observePositionDialog();interceptPositionSubmit();injectTradingView();await refreshContexts();await refreshPortfolioQuotes({force:true});window.addEventListener('neon:financechange',()=>{renderAllowanceIndicators();renderTradingViewPicker();});window.addEventListener('neon:phase9a-contextchange',()=>{renderAllowanceIndicators();if($('#pageFinance')?.classList.contains('active'))refreshPortfolioQuotes();});window.addEventListener('neon:phase9b1-page',e=>{if(e.detail?.page==='pageFinance'){renderAllowanceIndicators();renderTradingViewPicker();refreshPortfolioQuotes();}});quoteTimer=setInterval(()=>{if($('#pageFinance')?.classList.contains('active'))refreshPortfolioQuotes();},2*60*1000);return{refreshContexts,refreshPortfolioQuotes,financeContextSnapshot};}
